mxe/mxe

- src/opencv-2-fixes-cmake.patch
- src/opencv-3-fixes-pkgconfig.patch
- src/opencv.mk
Tested with x86_64-w64-mingw32.static and x86_64-w64-mingw32.shared.
Cherrypicks an upstream commit that cleanups the pkg-config file.
Also removes the version postfix on Windows dll's (matching other platforms).
These changes allows us to easilly support shared builds.
Removing the postfix avoids breaking programs that only link
to a subset of opencv modules, everytime a new version is released.
It should be noted that OpenCV forces static linking of libopencv_ts.
There are also 3 files that are left at usr/<triplet>/ that this commit does not
attempt to fix (LICENSE, OpenCVConfig.cmake and OpenCVConfig-version.cmake).
They cannot be moved to lib/ because a different OpenCVConfig.cmake is placed
there. On Ubuntu, for example, those cmake files are in /usr/share/OpenCV/.
> OpenCV: Fix paths and add shared support

- index.html
- src/libepoxy.mk
- src/xorg-macros.mk
This adds libepoxy (and the required xorg-macros), a modern alternative to GLEW.
PS: I noticed that there are many packages with quite similar $(PKG)_UPDATE parts, for example many github projects. Would it be a good idea to create some common templates for these cases?
> Add libepoxy

- src/glib.mk
- src/mingw-w64-2-netioapi-winxp.patch
Recently, a Performous user notified me that Performous does not run under Windows XP anymore, because the function if_nametoindex was not found in iphlpapi.dll. This happens because glib in MXE is build in a way to use the system if_nametoindex instead of its own replacement.
This branch tries to fix that. Part of the reason why compilation of glib failed is a conflicting definition of if_nametoindex in the mingw-w64 headers and glib sources. I checked with mingw-w64 upstream and their trunk has this fixed: If the API version is lower then Vista, those functions are not exposed and there is no conflict in glib.
Unfortunately, the structure of those header files changed very much in mingw-w64 trunk, so cherry-picking patches is not really possible. Therefore, since this will be fixed …
> Make glib run on WinXP again

- index.html
- src/readline.mk
- src/termcap.mk
This fixes runtime problems with applications using readline.
For example, backspace does not work. This is because
pdcurses, which readline currently uses to get information about a
terminal, does not really implement tgetent() and friends; they are only
stubs. Google "pdcurses readline backspace" for more information.
First I tried using ncurses instead, but then the application crashes.
I did not try to debug.
I simply added libtermcap and made readline use that. Yes, it is
ancient, but it works fine...
> Add package termcap, and make readline use it instead of pdcurses.

- src/polarssl-1-CVE20151182.patch
Temporary patch this until a new release of polarssl is made available. See:
https://polarssl.org/tech-updates/security-advisories/polarssl-security-advisory-2014-04
> Add fix for Polarssl CVE-2015-1182

- src/physfs.mk
This pull request enables a shared library build for PhysicsFS.
The following are all true in my MXE instance:
1. test-physfs.exe links and successfully runs under Wine 1.6.
2. In a shared build, only libphysfs.dll is present in `bin` and an import library is present in `lib`
3. In a static build, neither the DLL nor the import library are present
The definition of `$(PKG)_BUILD_SHARED` is largely copied from the existing build definition, with a few tweaks to turn off the static build.  I'd appreciate any suggestions to reduce the copy-paste.
> Enable shared build for PhysicsFS

- src/glib.mk
- src/qtbase.mk
- src/sdl2_gfx.mk
These are some fixes necessary in a (reasonably) clean build environment. Tested on an fresh Debian wheezy install.
- glib doesn't build without zlib any more, so provide a native version when building native glib tools
- sdl2_gfx tries to run aclocal-1.?? when running make since the timestamps between configure and Makefile.* are strange, so we rebuild everything with the installed automake tools...
- Somehow, sometimes, qtbase decides to link using gold, but gold only works for ELF. This can be fixed by disabling gold altogether...
> Fixes for clean build environment

- src/ncurses.mk
this fixes a bug which caused any GUI app which linked with ncurses
(e.g. when using caca/ffmpeg/libxine libs) to spawn a console window
even if ncurses wasn't initialized.
see github PR #636
> ncurses: update to e14300b

- src/mman-win32.mk
This updates the the checksum and version to the latest commit...
If you're not willing to change to the latest commit, you could change the URL to:
https://github.com/witwall/mman-win32/archive/3421c28e753c38d24a2e27c111b1c9b4601ebe7d.zip
Rather than keeping:
https://github.com/witwall/mman-win32/archive/master.tar.gz
That master.tar.gz is probably always pointing at the latest commit.
> Updated mman-win32

- src/mman-win32.mk
> mman-win32.mk download .tar.gz rather than .zip

- src/mman-win32.mk
This has been tested and works fine now.
I tried to rebuild every package today while I was away. There were a few errors on the last adjustments in mman-win32.mk. They've now been resolved. Changes to other packages may be coming up.
> Fixed errors in mman-win32.mk

- src/glew.mk
1. pkg-config wrongly adds the flag `-I/usr/include`, creating conflict with system headers.
2. cflags contains a define on static builds, so it must come before sources when compiling the test.
> Fix compilation of GLEW

- src/opencsg-1-fixes.patch
- src/opencsg.mk
This updates OpenCSG to the latest library version.
The existing patch that modifies the qmake files did not apply anymore, so I've updated that by applying the changes to the new project files manually.
* Checked with `i686-w64-mingw32.static` and `x86_64-w64-mingw32.static` targets
* Works with the OpenSCAD build
> Update OpenCSG to version 1.4.0.

- src/postgresql-2-autoconf-min-version.patch
the original configure.in warns if autoconf version is less than 2.63, but
patch 1 removes this warning. this patch adds that requirement using AC_PREREQ
on debian systems where both old/new versions of autoconf are installed,
a script is used to determine which version to use. adding AC_PREREQ to
configure.in helps the script choose the correct version.
the system should already have such version since MXE itself requires 2.67
see issue #672
> postgresql: require/hint minimum autoconf version 2.63

- src/lua.mk
- src/luabind-1-cmakelists.patch
- src/luabind-7-compatibility-Lua-macro.patch
- src/luabind.mk
- src/luajit.mk
LuaJIT 2.0.4 was released on May 14, 2015. It has various bug fixes over 2.0.3 - an update is recommended. See [the changelog](http://luajit.org/changes.html).
Lua 5.3 was released on Jan 12, 2015. Its [main new features](http://www.lua.org/manual/5.3/readme.html#changes) are integers, bitwise operators, a basic utf-8 library, and support for both 64-bit and 32-bit platforms.
Package luabind was changed to be compatible with Lua 5.3.0:
* do not use macro LUA_COMPAT_ALL. Lua 5.3 respects macros
LUA_COMPAT_5_2 and LUA_COMPAT_5_1 and ignores macro
LUA_COMPAT_ALL.
* Instead, include needed compatibility defines into header
luabind/config.hpp. Side effect of this is that C++ code
using luabind doesn't need to define LUA_COMPAT_ALL.
This definition was removed from the example of luabind.
> update Lua to 5.3.0 and LuaJIT to 2.0.4

- src/a52dec.mk
Otherwise imaxabs() and other functions in _mingw.h will not
be inlined and produce link error
> Enable ISO C90 inline for i686-w64-mingw32.shared

- src/devil-2-il.patch
Devil attempts to use the `restrict` keyword, even when building in C++ mode. Technically, `restrict` isn't defined in the C++ standard.
> Add Devil patch

- src/libgcrypt-2-no-git.patch
When reconfiguring libgcrypt using `autoconf`, libgcrypt calls `git` to determine what revision hash and number it's on. Most people won't see an issue, because the build directory is, by default, in a subdirectory of the mxe repo and `git` will use mxe's revision log and hashes. However, if the build directory is changed to `/dev/shm` for I/O performance reasons, then because there is no git repo there, the build will fail.
Specifically, `autoconf` will go through and ignore the error, but when building `versioninfo.rc` using `windres`, the version number will be listed as `1,6,3,` because revision number (hard-coded to 4091 below) will be blank, resulting in a syntax error.
> Don't use git when building libgcrypt.

- src/dcmtk-3-pointer-fixes.patch
- src/dcmtk.mk
The fix for building 64-bit dcmtk in #611 was to ignore the cast issue (an 8-byte pointer was being cast to a 4-bit integer). The proper fix is to fix the underlying issue.
In this case, the errors are in print-statements, so there should be no functionality change.
> Fix building dcmtk on 64-bit platforms.

- src/lua.mk
Lua 5.3.1 was released on 17 Jun 2015. It is a [bug-fix](http://www.lua.org/bugs.html#5.3.0) release of Lua 5.3.
> update Lua from 5.3.0 to 5.3.1

- tools/build-pkg.lua
This tool builds all packages for all targets and generates `*.tar.xz` and `*.deb` files. The latter ones can be uploaded to APT repository and installed to Debian machines.
build-pkg.lua was previously known as mxedeb.lua
See also:
* http://mxe.redjohn.tk/
* https://github.com/starius/mxedeb
* https://lists.nongnu.org/archive/html/mingw-cross-env-list/2015-02/msg00010.html
* https://lists.nongnu.org/archive/html/mingw-cross-env-list/2015-03/msg00001.html
> add tool build-pkg.lua

- tools/build-pkg.lua
Fix description of the script: replace "DEB packages" with "binary packages".
> build-pkg: remove old name "mxedeb"

- src/qt3d.mk
- src/qtactiveqt.mk
- src/qtconnectivity.mk
- src/qtdeclarative.mk
- src/qtenginio.mk
- src/qtgraphicaleffects.mk
- src/qtimageformats.mk
- src/qtlocation.mk
- src/qtmultimedia.mk
- src/qtquick1.mk
- src/qtquickcontrols.mk
- src/qtscript.mk
- src/qtsensors.mk
- src/qtserialport.mk
- src/qtservice.mk
- src/qtsvg.mk
- src/qtsystems.mk
- src/qtwebchannel.mk
- src/qtwebengine.mk
- src/qtwebkit.mk
- src/qtwebsockets.mk
- src/qtwinextras.mk
- src/qtxlsxwriter.mk
- src/qtxmlpatterns.mk
qmake is invoked with removed debug options as a workaround for
https://bugreports.qt-project.org/browse/QTBUG-30898
This fix uses the same mechanism used for qtbase.mk in b30e9d41.
Fixes mxe/mxe#751.
> various qt packages: fix libraries having debug postfix in pkg-config files

- src/gcc-3-codecvt_byname_export.patch
exports symbols neccessary for any application declaring the codecvt_byname facet, which affects Boost in MXE.
it has been fixed in GCC 5.2
> GCC: Export codecvt_byname and codecvt symbols for mingw32.

- src/mingw-w64.mk
Any attempt to generate headers for an idl that imports a "standard" idl
will fail if the respective idl files are not in the include path.
MingW-W64 copies the idl .h files but not the idl files unless --enable-idl
is used.
> mingw-w64: Use --enable-idl so widl can be used.

- .gitignore
- Makefile
- index.html
Currentl, the index page pulls version information from all the *.mk files, which is quite a lot of data and requests. This introduces a cache for this data:
- A makefile target to generate the cache
- JavaScript code that reads the cache and falls back to the old style, if it isn't found
- A bit unrelated: Shorten long version numbers, like in build-matrix.
On my slow DSL connection, this is the difference for loading index.html:
Without cache: 372 Requests, 779,42 KB, 37,30 s
With cache: 6 Requests, 198,27 KB, 5,11 s
I don't know how useful this is for mxe.cc, but it may be possible to move the GitHub Pages hosting to another branch (gh-pages) and commit versions.json there...
Test page: http://buildbox.23.gs/mxe/#packages
> index.html versions cache

- src/libgcrypt-3-no-serial-tests.patch
automake < 1.12 didn't have serial-tests and gives an error if it sees this, but for automake >= 1.13 serial-tests is required so we have to include it. Solution is to test for the version of automake (by running an external command) and provide serial-tests if necessary. I've tested this successfully for all targets with automake 1.11.6. Could someone test it with automake >= 1.13, please?
See #681
See https://www.redhat.com/archives/libguestfs/2013-February/msg00102.html
> fix libgcrypt on x86_64 (automake < 1.12)

- Makefile
I was never really happy with the way targets are serialized, it's fighting against `make` (causing issues like #234 and #219), and the target header isn't particularly informative. This fixes #234 and should also provide a speedup when building all targets simultaneously.
Download rules are now pre-requisites of build rules to stop multiple download attempts and allow downloading while dependencies are being built. All build logs have a target suffix.
More work is needed on #219, since download rules are always outdated unless a marker file is used and the checksum will be calculated more than necessary. I'll look at this separately as I also want to allow script only packages.
> Makefile: build targets in parallel

- src/qtbase.mk
This allows cmake-using programs to find Qt5 components.
> qtbase: Append Qt5 cmake dir to CMAKE_PREFIX_PATH.

- index.html
- src/qhttpengine.mk
QHttpEngine is a small, lightweight library that provides a set of classes for creating HTTP servers. It is based on Qt 5 and will be used in the next version of [NitroShare](https://github.com/nitroshare/nitroshare-desktop) to provide a local API.
The library can be built both as a static and shared library and I have tested both. Because the library uses the CMake `find_package()` command, it is necessary to provide CMake with the path to `Qt5NetworkConfig.cmake`. I have done this via:
-DCMAKE_PREFIX_PATH='$(PREFIX)/$(TARGET)/qt5/lib/cmake'
> Add qhttpengine library.

- tools/build-pkg.lua
Changes:
* Debian Wheezy (and Ubuntu 12.04 LTS) compatibility
* blacklist `usr/share` and `usr/installed/check-requirements`
* add target to log lines about broken packages
> several improvements of build-pkg.lua

- index.html
- src/pire-1-remove-custom-isatty.patch
- src/pire-2-disable-samples-inline.patch
- src/pire.mk
PIRE is Perl Incompatible Regular Expressions library.
This library is aimed at checking a huge amount of text against
relatively many regular expressions. Roughly speaking, it can
just check whether given text maches the certain regexp, but
can do it really fast (more than 400 MB/s on our hardware is
common). Even more, multiple regexps can be combined together,
giving capability to check the text against apx. 10 regexps in
a single pass (and mantaining the same speed).
Pire was developed in Yandex (http://company.yandex.ru/) as a
part of its web crawler.
Homepage: https://github.com/yandex/pire
> add package pire

- src/qtwebkit.mk
The package qtwebkit will fail to build if sqlite hasn't been built. Normally, sqlite is pulled in by qtbase, but if it's disabled there, qtwebkit still needs it.
> QtWebKit depends on SQLite even if SQLite support is turned off in QtBase

- src/bfd-1-disable-subdir-doc.patch
* makeinfo fails when the documentation is built.
* MXE tries not to build a documentation
close #711
> bfd: disable doc

- src/glib-1-fixes.patch
The reason of this patch is not clear, because glib.mk already depends on gettext.
It introduces a (hard to find) difference between mxe and native linux
builds: On Linux, glib includes gettext header libintl.h, but not on
mxe.
> Remove 'removal of gettext' from glib patch

- tools/build-pkg.lua
Bad behaviour prior to this commit:
1. The package is broken: pango
2. Package sdl_pango depends on broken pango
3. When t4k_common (which depends on sdl_pango) is built, pango is tried to build again.
This issue was caused by the error fixed in this commit: if a package A depends on a broken package B, then the package A is also BROKEN. So if a package C depends on package A, then all of them are broken:
```
(*)B <- A <- C
```
B is not "rebuilt" for C.
> build-pkg: pkgs with broken deps are also broken

- src/pcl-1-cmake-policy-cmp0017.patch
Add "cmake_policy(SET CMP0017 NEW)" to CMakeLists.txt
$ cmake --help-policy CMP0017
> Starting with CMake 2.8.4, if a cmake-module shipped with CMake (i.e.
> located in the CMake module directory) calls include() or
> find_package(), the files located in the the CMake module directory
> are preferred over the files in CMAKE_MODULE_PATH.  This makes sure
> that the modules belonging to CMake always get those files included
> which they expect, and against which they were developed and tested.
> In call other cases, the files found in CMAKE_MODULE_PATH still take
> precedence over the ones in the CMake module directory.  The OLD
> behaviour is to always prefer files from CMAKE_MODULE_PATH over files
> from the CMake modules directory.
Error message:
```
CMake Error at …
```
> fix pcl build

- tools/build-pkg.lua
2.23 -> 2.23jessie | 2.23wheezy
Package mxe-requirements has different dependencies for
Wheezy and Jessie. APT server reprepro doesn't allow to
add two different packages with same name and version.
> build-pkg: add release to mxe-requirements version

- src/pango-1-fixes.patch
- src/pango.mk
Remove patches:
* the patch disabling DllMain in pango-utils.c
(There is no DllMain pango-utils.c in pango 1.37.4)
* the patch disabling forced shared build for win32
(Can't find this code in configure.ac; also the build is'not
forced to be shared, so it is Ok to remove the patch)
* patches related to modules (there are no more eodules)
Fix patches with changed context
> update pango to 1.37.4

- src/opencv-4-reverse-deps-sublist.patch
Reorder libraries in opencv.pc so that a depender before a dependee.
close #735
> fix linking error in opencv

- src/qhttpengine-1-decrease-required-cmake-ver.patch
Fix build for CMake 2.8.9, which is used in Debian Wheezy.
> qhttpengine: decrease required cmake ver

- src/a52dec.mk
aclocal.m4 generated with old version of libtool break the build
https://lists.nongnu.org/archive/html/mingw-cross-env-list/2015-08/msg00021.html
close #798
> a52dec: rm aclocal.m4

- tools/build-pkg.lua
see #842 
Broken symlinks detected:
```
usr/bin/i686-w64-mingw32.static-llvm-config
usr/i686-w64-mingw32.static/lib/libharfbuzz_too.a
usr/i686-w64-mingw32.static/bin/gda-list-config.exe
usr/i686-w64-mingw32.static/bin/gda-list-server-op.exe
usr/i686-w64-mingw32.static/bin/gda-sql.exe
usr/bin/i686-w64-mingw32.static-lrelease
```
(Only for `i686-w64-mingw32.static`.)
> Build pkg fix filenames with spaces

- src/agg.mk
This reverts commit c9afbabda56635bb1f2f49090a0c2091d4ab1340.
AGG project's site was restored.
See #386
> Revert "package agg: use mxe pkg mirror until project relocates"

- tools/build-pkg.lua
`mxe-requirements` package doesn't install any files therefore fakeroot is not required. Because no files were created with fakeroot, database file `deb.fakeroot` did not exist.
close #840
> build-pkg: no build mxe-requirements with fakeroot

- src/nsis.mk
> Currently you can't change NSIS_MAX_STRLEN without re-compiling NSIS.
> This was a problem because some NSIS projects would require the special
> build and some wouldn't, and sometimes we'd compile a project that
> required the special build, with the normal MakeNSIS build.
(from http://nsis.sourceforge.net/SetReqStrLen:_Allow_compile_w/_8192_special_build_only)
See also http://nsis.sourceforge.net/Special_Builds#Large_strings
> nsis: increase NSIS_MAX_STRLEN to 8192

- src/suitesparse.mk
Old URL is 404. Parent URL redirects to http://faculty.cse.tamu.edu/davis/research.html
> fix suitesparse download URL

- src/fftw.mk
From fftw-3.3.4/Makefile.am:
> when using combined thread libraries (necessary on Windows), we want
> to build threads/ first, because libfftw3_threads is added to
> libfftw3.
>
> Otherwise, we want to build libfftw3_threads after libfftw3
> so that we can track the fact that libfftw3_threads depends upon
> libfftw3.
>
> This is the inescapable result of combining three bad ideas
> (threads, Windows, and shared libraries).
When compiling with combined threads, all thread related functions
are added to main libraries (libfftw3, libfftw3f, libfftw3l). I have
checked their existance in libfftw3-3.dll by using nm.
close #872
^^ Instead of adding -lfftw3_threads to fftw*.pc files, add
thread related functions to main fftw3 lib.
> fftw: compile with combined thread libraries

- src/libjpeg-turbo-2-install-DLL-to-bin-libjpeg-turbo.patch
- src/libjpeg-turbo.mk
Enable shared build. It was disabled because DLLs were installed to lib/bin.
see #826
> libjpeg-turbo: install DLL to bin/libjpeg-turbo

- index.html
- src/glib-2-remove-runtime-warning-gtkapplication.patch
- src/gtk3-1-fixes.patch
- src/gtk3-test.c
- src/gtk3.mk
- src/gtkmm3-test.cpp
- src/gtkmm3.mk
Pango has been updated to 1.37.4 in 24cf97dbdd62ece0ea0b39cf33694a8804352bd1
Side effects:
* mute function g_win32_run_session_bus of glib (see the thread)
* add new external dependency: gdk-pixbuf
Original thread:
https://lists.nongnu.org/archive/html/mingw-cross-env-list/2015-08/msg00009.html
> add packages gtk3 and gtkmm3

- src/muparser.mk
[Original muparser location](http://sourceforge.net/projects/muparser/) forwards to [Google Code](https://code.google.com/p/muparser/), which in turn forwards to [Github](https://github.com/beltoforion/muparser).
Version 2.2.3 can't be found on Github, that is why it was updated to 2.2.5.
Updater script updated as well.
Build passes on Debian Jessie.
> muparser: update upstream URL and version to 2.2.5

- index.html
- speexdsp.mk
The Speex developers split the project into two separate repositories in 1.2rc2. This adds the spun-off SpeexDSP library to MXE, so projects like mine (Aleph One) can continue to use the functionality previously covered by the "speex" package.
> add package speexdsp

- src/protobuf.mk
This tool is needed by some packages using protobuf (e.g., mosh).
> protobuf: install prefixed protoc tool

- src/pkgconf.mk
in pkgconf.cmake so that pkgconf can be found through cmake at first run.
> pkgconf: added option CACHE PATH for PKG_CONFIG_EXECUTABLE 

- tools/build-pkg.lua
`mxe-conf` is a special package added to dependencies of other packages implicitly, not via `$(PKG)_DEPS`. Tool `build-pkg` used to find dependencies in `$(PKG)_DEPS` only. Now it looks in $(MXE_CONF_PKGS) as well. This code was adopted from `PKG_TARGET_RULE`.
see #890
> build-pkg: add MXE_CONF_PKGS to deps of packages

- src/openexr-2-64-bit-fixes.patch
This allows building on x86_64-w64-mingw32.shared (at least).
> Add patch to openexr to fix pointer conversion.

- index.html
- src/libmysqlclient-1-use-comp-err-tool-built-in-native-build.patch
- src/libmysqlclient-2-fix-extra-qualification-handshake.patch
- src/libmysqlclient-3-fix-case-in-headers-and-libs.patch
- src/libmysqlclient-4-define-missing-types.patch
- src/libmysqlclient-5-macro-native-win32.patch
- src/libmysqlclient.mk
Based on proposal #755 
Shared build was disabled because of [linking errors](https://gist.githubusercontent.com/starius/a6f651506a90272714fb/raw/8a9e66971ffbf22256fd93cf9e2b94ae3782272e/libmysqlclient_i686-w64-mingw32.shared) in test executable, caused by stdcall/cdecl mismatch. Probably it can be fixed using by creating `def`-file or by passing `--add-stdcall-alias` or `--kill-at`. Help is appreciated. See http://stackoverflow.com/a/9032772
MySQL needs tool `comp_err` to generate header `mysqld_error.h`. This tool is generated by the build, so it is to be compiled natively. CMake has command `EXPORT` for this scenario. The package is built twice: (1) natively, for `comp_err`, which is exported to (2) cross-build, using `comp_err` in normal CMake commands like `ADD_CUSTOM_COMMAND`. Read …
> add package libmysqlclient

- src/qtbase-2.patch
This allows qtbase to build successfully when configured with -no-libpng or -no-libjpeg. See the following for more information:
http://buildroot-busybox.2317881.n4.nabble.com/PATCH-v2-qt-qt5base-Fix-INCLUDE-PATH-when-no-JPEG-PNG-support-tt107094.html#none
https://codereview.qt-project.org/gitweb?p=qt/qtbase.git;a=commitdiff;h=7f282aa9f718389199b95b7f53ecd6401172fcc6;hp=954f0d93976362d29044439e4eaa11d2dff16624
> Add qtbase patch to allow building without JPEG or PNG support

- Makefile
MXE recongized file `src/lua-rapidjson-1-use-unix-file-functions.patch` as a patch for `lua`, however it was intended to be a patch for `lua-rapidjson`. Patch filename pattern was `src/$(1)-*.patch`. `*` captured "rapidjson-1-use-unix-file-functions".
Currently `*` was replaced with `[0-9]*` to require patch name starting with a digit.
Tested on all packages of `i686-w64-mingw32.static` target.
see #921
> require patch number to start with a digit

- Makefile
Check with command `gdk-pixbuf-csource --help`.
`make check-requirements` succeeds on the machine with native `gdk-pixbuf` installed.
`make check-requirements` fails on the machine without native `gdk-pixbuf` installed:
```
$ make check-requirements
[create settings.mk]
[using autodetected 6 job(s)]
[check requirements]
Missing requirement: gdk-pixbuf-csource
Please have a look at "index.html" to ensure
that your system meets all requirements.
Makefile:300: recipe for target '/mxe/usr/installed/check-requirements' failed
make: *** [/mxe/usr/installed/check-requirements] Error 1
```
see #927
> check-requirements: check for native gdk-pixbuf

- src/blas.mk
Transient fix for #922
see http://lists.nongnu.org/archive/html/mingw-cross-env-list/2015-10/msg00009.html
Tested against whole `i686-w64-mingw32.static` target.
> update & fix blas

- src/openscenegraph-3-fix-pointer-to-int-conversion-on-64bit.patch
there is an integer type that is guaranteed to be big enough to hold a pointer (but it's only available since C++11 and C99):
* [Fixed width integer types (since C++11) - cppreference.com](http://en.cppreference.com/w/cpp/types/integer])
* [Fixed width integer types (since C99) - cppreference.com](http://en.cppreference.com/w/c/types/integer])
> use better type for pointer cast

- src/vmime.mk
vmime uses a file from the src-directory of mxe but references it using
a relative path that is only working if the temporary build directory is
inside the mxe project path at the fixed position.
> fix project path for vmime extra file

- src/mxe-conf.mk
> cmake wrapper: don't pass -DCMAKE_TOOLCHAIN_FILE to cmake when  with --build

- Makefile
sometimes it's necessary to not build inside the mxe folder. The
variable MXE_TMP can be used to change the base directory for creating
tmp directories that are used for building.
Rationale: when using virtualbox to build the cross-compile environment
and the mxe project is in a shared folder, at least stripping is not
working because of an internal error of the shared filesystem.  So the
solution is to change the tmp-directory to a place inside the VM.
> add variable to define directory for tmp-directories

- index.html
witty.sourceforge.net redirects to www.webtoolkit.eu
> change Wt homepage to http://www.webtoolkit.eu

- index.html
Cataclysm: Dark Days Ahead is happy to use MXE for its daily builds and stable builds. You guys rock!
> Adding Cataclysm: Dark Days Ahead in the list of projects who use MXE

- index.html
- src/lzma-1-include-stdio.h.patch
- src/lzma-2-mystring-include-windows.patch
- src/lzma.mk
- src/upx-1-fix-logging.patch
- src/upx.mk
**UPX** is a free, portable, extendable, high-performance executable packer for several executable formats.
http://upx.sourceforge.net
The **LZMA SDK** provides the documentation, samples, header files, libraries, and tools you need to develop applications that use LZMA compression.
http://www.7-zip.org/sdk.html
UPX depends on source of [UCL](http://www.oberhumer.com/opensource/ucl/) and LZMA. Tarballs with source of these packages are unpacked when UPX is built.
> add packages lzma and upx

- index.html
This is to provide gdk-pixbuf-csource.
> gdk-pixbuf2-devel not gdk-pixbuf-devel

- src/mxe-conf.mk
Now dlfcn-win32 can't detect wine.
From log/dlfcn-win32_i686-w64-mingw32.static:
static: yes
shared: no
wine:
Previously wine was set to "yes wine".
fix #995
> disable wine

- tools/build-pkg.lua
See https://github.com/mxe/mxe/pull/966#issuecomment-153712570
```
$ grep '.a file but no' log                                                                                               
[build-pkg]     Shared item x86_64-w64-mingw32.shared~yasm installes .a file but no .dll
[build-pkg]     Shared item x86_64-w64-mingw32.shared~termcap installes .a file but no .dll
[build-pkg]     Shared item x86_64-w64-mingw32.shared~polarssl installes .a file but no .dll
[build-pkg]     Shared item x86_64-w64-mingw32.shared~nlopt installes .a file but no .dll
[build-pkg]     Shared item x86_64-w64-mingw32.shared~mman-win32 installes .a file but no .dll
[build-pkg]     Shared item x86_64-w64-mingw32.shared~aspell installes .a file but no .dll
[build-pkg]     Shared item i686-w64-mingw32.shared~yasm …
```
> build-pkg: check shared targets install dlls; do not create empty packages

- index.html
- src/cloog.mk
- src/gcc.mk
- src/isl.mk
- src/libmysqlclient-1-fixes.patch
See #964
See da82d07dbeca23087aa4351914cf4b890c1d3972
See c96a007c6a4b03ca8d43c2ed848c47832f9e2baf
See 7882944eb99fa14bb82f3045896668a68f8c68a7
> Downgrade gcc to 4.9

- src/coin.mk
Per https://github.com/mxe/mxe/pull/966#issuecomment-157644451, I have removed the disabling of features.  I tested it with a clean MXE installation that only had gcc installed.
> Coin3D: do not disable features by default

- Makefile
- plugins/README.md
- plugins/apps/keepassx-1-don-t-discard-config-set-by-qmake.patch
- plugins/apps/keepassx.mk
- plugins/custom-qt-min/overrides.mk
- plugins/gcc52/gcc52-overlay.mk
- plugins/native/autoconf.mk
- plugins/native/automake.mk
- plugins/native/bison.mk
- plugins/native/coreutils.mk
- plugins/native/flex.mk
- plugins/native/gettext.mk
- plugins/native/gperf.mk
- plugins/native/intltool.mk
- plugins/native/libiconv.mk
- plugins/native/libtool.mk
- plugins/native/m4.mk
- plugins/native/make.mk
- plugins/native/sed.mk
Following on from #881 and #925, this removes the optional native builds and provides a new way to handle such things.
Basic usage is to drop some `*.mk` files in a directory and set `MXE_PLUGIN_DIRS='path1 path2 ...'`. Building and updates work as expected, but I haven't tested heavily enough to expose any edge cases.
```
$ make keepassx MXE_PLUGIN_DIRS='plugins/apps' -j4
[using autodetected 6 job(s)]
[check requirements]
[build]     mxe-conf               x86_64-apple-darwin14.5.0
[done]      mxe-conf               x86_64-apple-darwin14.5.0                              312 KiB        0m7.361s
[build]     gmp                    x86_64-apple-darwin14.5.0
[build]     pkgconf                x86_64-apple-darwin14.5.0
...
[done]      freetds                i686-w64-mingw32.static …
```
> MXE Plugins

- src/libmysqlclient-2-posix-fixes.patch
- src/postgresql-4-posix-threads.patch
Both of these applications assume pthreads isn't available on Windows and redefine those functions, resulting in duplicate definitions.
> Fix MySQL and PostgreSQL posix build

- index.html
- src/cmake.mk
- src/mxe-conf.mk
First step in standardising cmake across MXE:
* install in MXE native path so only visible to MXE sessions and wrapper scripts
* remove from requirements
* no MXE patches or pkg updates yet
Should provide a common baseline for [cmake issues](https://github.com/mxe/mxe/labels/cmake)
> Build native version of cmake

- src/qtwebkit-1-fixes.patch
It is not needed in ASCII/UTF-8 file
> remove Byte Order Mark (BOM) from a patch

- Makefile
It is needed for #976, to unpack Debian package with GeoIP.dat downloaded from https://packages.debian.org/jessie/all/geoip-database/download
`tar xf` instead of `tar xzf` / `xz -dc '$(1)' | tar xf -` because Debian package can contain `data.tar.gz` or `data.tar.xz`. Probably this code can be rewritten better.
> add unpacker for .deb files

- Makefile
Fix for issue which has been described in https://github.com/mxe/mxe/issues/782#issuecomment-164198871
> #782 fix, wrong checksum calculation command for OSX

- tools/build-pkg.lua
Otherwise empty dependency produces no `.deb` file preventing non-empty package from being installed.
Example: non-empty package `gcc` depends on empty package `mingw-w64`.
> build-pkg: build empty dependencies of non-empty

- tools/build-pkg.lua
Debian packages with "Depends: " do not work:
> Reading package lists... Error!
> E: Problem parsing dependency Depends
> E: Error occurred while processing mxe-source (NewVersion2)
> E: Problem with MergeList /var/lib/apt/lists/pkg.mxe.cc_repos_apt_debian_dists_wheezy_main_binary-amd64_Packages
> E: The package lists or status file could not be parsed or opened.
> build-pkg: do not provide empty dependency list

- tools/patch-tool-mxe
Previously patch-tool-mxe produced the following diffs:
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 0000000..0000000 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
```
patch tool refused to apply this patch:
```
The next patch would create the file CMakeLists.txt,
which already exists!  Assume -R? [n]
```
This commit replaces 0000000..0000000 with 1111111..2222222.
> patch-tool-mxe: do not replace object id with 000

- tools/build-pkg.lua
The installation failed with the following note:
> Noting disappearance of mxe-requirements,
> which has been completely replaced.
Add an empty file `mxe-requirements.dummy.$release` to prevent this.
> build-pkg: fix .deb installation

- Makefile
see #1085. 
Dollars signs are okay in some places, but they don't play well with `eval` or variable targets.
> Makefile: error on paths with dollar signs

- Makefile
* use short form for build status
* use full hash and refs for logs
* ~~add `TERM` to env whitelist (`git log` assumes a terminal)~~
closes #1095
> Add git commit hash to log and build message

- index.html
- src/agg.mk
Homebrew switched to archived version of agg tarball: https://github.com/Homebrew/homebrew/commit/27b37d1ce337b02176e0b00092ab80dbe74326aa
(Unfortunately web.archive.org is banned by authorities in Russia at the moment. I hope this will change.)
agg.sourceforge.net was proposed in the agg mailing list: http://sourceforge.net/p/vector-agg/mailman/message/34712672/
fix #1077
> agg: replace broken site antigrain.com with mirror

- tools/patch-tool-mxe
Otherwise it provides binary diff for jack/waf file, which is a mix of Python and tar.
> patch-tool-mxe: always output text diffs

- src/libgnurx.mk
The original libgnurx is based off glibc 2.5, which has multiple known vulnerabilities, including but not limited to:
- CVE-2013-0242: Buffer overflow in the extend_buffers function in the
regular expression matcher (posix/regexec.c) in glibc, possibly 2.17
and earlier, allows context-dependent attackers to cause a denial of
service (memory corruption and crash) via crafted multibyte
characters.
> Use my fork of libgnurx

- tools/s3-fetch-and-sync
Plugins like gcc52 cause the current file to be deleted so just use a whitelist of directories.
closes #1135
> add selected plugins to backup download

- index.html
- src/libieee1284-1-ssize_t.patch
- src/libieee1284-2-dll.patch
- src/libieee1284-3-windows-header.patch
- src/libieee1284-4-getversion.patch
- src/libieee1284-5-pkg-config.patch
- src/libieee1284.mk
Please merge this commit which adds the libieee1284 library. At the sigrok project we'd like to use this library to connect with some older devices.
The four patches have also been posted to the libieee1284 mailing list for inclusion in the next release.
> new package: libieee1284

- Makefile
See https://github.com/mxe/mxe/issues/1108#issuecomment-169556116
See https://github.com/mxe/mxe/issues/1112
From log:
```
perl --version 2>&1 | head -3
This is perl 5, version 18, subversion 2 (v5.18.2) built for x86_64-linux-gnu-thread-multi
(with 41 registered patches, see perl -V for more detail)
```
> print Perl version to log

- src/pcre.mk
Application EiskaltDC++ requires pcre with C++ support.
See https://github.com/mxe/mxe/pull/1127#issuecomment-169418284
All packages were built successfully on all 4 targets (cb8a7deb8fe5259b89ad2e5a986b477fa5808162 + this commit). Then rebased.
/cc @pavelvat
> pcre: enable C++

- src/nsis-1-fixes.patch
- src/nsis.mk
see https://github.com/mxe/mxe/issues/1163
Build is successful. `usr/bin/i686-w64-mingw32.static-makensis` was tested with packing NPG-exporer.
> nsis: update from 2.46 to 2.50

- tools/mxe-activate
* remove `build-only*` - too low level for general use
* add new patch related commands and catch-all completions
* `mxe-make` alias is more descriptive
> mxe-activate: update completions and change alias to mxe-make

- src/mxe-conf.mk
> mxe-conf: prevent touching a file in readonly dir

- tools/build-pkg.lua
Produce a warning if MXE_DIR != /usr/lib/mxe
When making a debug build, it is better to get a warning than set MXE_DIR manually each time.
> build-pkg: set MXE_DIR automatically

- src/binutils.mk
See:
http://lists.nongnu.org/archive/html/mingw-cross-env-list/2016-01/msg00013.html
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=813144
> binutils: revert update and ignore 2.26

- src/binutils.mk
Since #1206 is going to cause a full rebuild anyway.
see: https://wiki.debian.org/ReproducibleBuilds/TimestampsInStaticLibraries
> binutils: enable deterministic archives

- src/coin-2-gcc-4.7.patch
- src/coin-test.cpp
This adds two bugfix patches that are present in Gentoo.  The latter one is necessary, as the name indicates, to compile cleanly with a newer version of gcc.  It adds a missing include.
> add Coin bug fixes from Gentoo

- src/qtbase-1-fixes.patch
`u' modifier ignored since `D' is the default (see `U')
This error is shown during builds of end-user programs.
> qtbase: update patch for fixing `ar' error:

- plugins/apps/tor-1-fixes.patch
Tor can be compiled without `mman-win32`, because it has own implementation of `mmap` using Windows API. But if `mman-win32` is installed, Tor tries to use it resulting in linking errors. (In MXE mman-win32 installs DLLs even for static targets!)
This is another case of [undeclared optional dependency](https://github.com/mxe/mxe/issues/1111) resulting in build failure.
See also https://trac.torproject.org/projects/tor/ticket/18360
> tor: fix linking errors if mman-win32 is installed

- src/aspell-1-fixes.patch
- src/aspell.mk
> aspell: fix shared linking, disable pthreads, and add archlinux patches

- src/cryptopp.mk
The pkg-config file is required for https://github.com/clementine-player/Clementine/blob/master/CMakeLists.txt#L62
> cryptopp: install pkg-config file

- Makefile
Dependencies of build-matrix.html were written without regarding plugins. It resulted in the following error on Debian Wheezy (which uses plugin "plugins/native/wheezy/"):
```
$ make build-matrix.html
make: *** No rule to make target `src/autoconf.mk',
needed by `build-matrix.html'.  Stop.
```
The following targets also need updating:
* cleanup-style
* cleanup-deps-style
* versions.json
> fix dependencies of build-matrix.html

- tools/nonetwork.c
`fflush(stderr)` [may be needed](http://mailman.linuxchix.org/pipermail/courses/2002-August/000691.html).
see https://github.com/mxe/mxe/pull/1270
> nonetwork: new line before the message and flush

- src/qtwebkit.mk
The outdated checksum is updated for the file: [http://ftp.fau.de/qtproject/community_releases/5.6/5.6.0/qtwebkit-opensource-src-5.6.0.tar.xz](http://ftp.fau.de/qtproject/community_releases/5.6/5.6.0/qtwebkit-opensource-src-5.6.0.tar.xz)
> Update the sha256 checksum for QtWebkit

- index.html
- src/googletest.mk
- src/protobuf.mk
Fix #1269. I have tested it for protobuf versions 2.6.1 and 3.0.0-beta-2. For version 3.0.0-beta-2 need to replace line:
```
cd '$(1)' && mv googletest-release-$(googletest_VERSION)/ gtest
```
on:
```
cd '$(1)' && mv googletest-release-$(googletest_VERSION)/ gmock
```
> add package googletest and update protobuf (fix #1269)

- index.html
- src/gst-plugins-good.mk
- src/libsoup-1-fixes.patch
- src/libsoup-test.c
- src/libsoup.mk
```libsoup``` required for ```clementine``` to play internet radio stations. 
After this need build again the package ```gst-plugins-good```, then there will be ```$(PREFIX)/$(TARGET)/bin/libgstsouphttpsrc.dll``` which need to add to gstreamer-plugins directory for clementine https://github.com/mxe/mxe/pull/1277.
```libsoup-1-fixes.patch``` contain workaround for disable build docs, because by default for correct work ./autogen.sh required install Debian package: ```apt install gtk-doc-tools```, but ```gtk-doc-tools``` not listed in http://mxe.cc/#requirements-debian
> add package libsoup

- src/qtbase.mk
The error: `g++: error: unrecognized command line option ‘-std=c++1y’`
Full log: https://gist.github.com/147a8e697b4be73dad0218598dab2608
The problem was solved by setting C++ version to C++11 explicitly.
> fix qtbase on Wheezy (don't use c++1y)

- src/libsoup.mk
On OSX, native `/usr/bin/krb5-config` is detected and tries to enable gssapi.
> libsoup: disable gssapi

- index.html
- src/libuv-1-fixes.patch
- src/libuv-test.c
- src/libuv.mk
Test binary works on Windows.
TODO: patch `libuv-1-fixes.patch` just copies dependencies from Makefile.am.
`LIBS` variable (in upstream version) becomes equal to `-lpthreads`.
From generated `Makefile.am`:
```make
am__append_4 = -lws2_32 -lpsapi -liphlpapi -lshell32 -luserenv
...
LIBS = -lpthread  $(am__append_4)
```
From `configure.ac`:
```ac
AS_IF([test "x$PKG_CONFIG" != "x"], [
AC_CONFIG_FILES([libuv.pc])
])
AC_CONFIG_FILES([Makefile])
```
Therefore, `Makefile` is generated after `libuv.pc`. Variables from `Makefile` don't affect `config.status` and `libuv.pc`.
The following work:
```
$ LIBS="-lpthread -lws2_32 -lpsapi -liphlpapi -lshell32 -luserenv" ./config.status --recheck
$ ./config.status libuv.pc
```
But how to extract that `LIBS` variable from `Makefile`?
> [WIP] add libuv

- index.html
needed for `build-pkg.lua`, installed as:
- `gtar` on Homebrew
- `gnutar` on MacPorts and Rudix
so will be selected by `tool` function
> add GNU Tar to requirements and specify OS X packages

- src/box2d.mk
The file was changed in upstream.
File pkg/box2d-2.3.1.tar.gz
(or https://github.com/erincatto/Box2D/archive/v2.3.1.tar.gz):
Old sha256: 2c61505f03ef403b54cf0e510d83d6f567e37882ad79b5b2d486acbc7d5eedea
New sha256: 75d62738b13d2836cd56647581b6e574d4005a6e077ddefa5d727d445d649752
Changes:
$ diff -r old/ new
Only in old/Box2D-2.3.1/Contributions/Platforms: Box2D.XNA.zip
Only in old/Box2D-2.3.1/Contributions/Platforms: Tizen.zip
Files Box2D.XNA.zip and Tizen.zip are not used in build, according to logs.
Removing them them seems to be safe.
fix #1319
> box2d: update sha256

- tools/build-pkg.lua
This pull request implements second and third passes of #1111. In original proposal, the second pass builds a package in a tree with all packages except itself and its followers and the third pass rebuilds a package in a tree with all packages built. The third pass seems to be more strict than second, so it was implemented here.
Build log: https://gist.github.com/starius/a165cbb474f4d9c1dd7e
(It is based on commit 62467d9d4dbb69aa632ae684b4a5a3f4c3b4a1ff.)
Package `fontconfig` breaks on the seconds pass.
> build-pkg: build a package second time in tree with all packages

- plugins/luarocks/luv-1-fixes.patch
- plugins/luarocks/luv.mk
i686-w64-mingw32.shared was tested on Windows XP with the [official example](https://github.com/luvit/luv/blob/master/README.md) of TCP echo server.
> add package luv to luarocks plugin

- src/jsoncpp.mk
Fix after 0bc73f739d7a8f2bc4e5100da62a0d894cbc9e38.
There is no -Werror=shift-negative-value in GCC 4.9.x.
> jsoncpp: fix build with GCC < 6.x

- src/proj-1-fixes.patch
For mingw, proj4 creates libproj-9.dll and GDAL library consider
this as missing dll. GDAL has a workaround to use PROJSO env
variable that allows to set proj-9.dll. But it is better if
proj library could simply output the dll with the other name
https://trac.osgeo.org/gdal/browser/branches/2.1/gdal/ogr/ogrct.cpp#L86
> proj4: libproj-0.dll is checked by GDAL if the platform is windows

- src/mman-win32.mk
The switch to using cmake in ca5bba6 also remove the ability to compile the library statically.
Also along the way (but not addressed in this PR), the renaming of mman.h to mman-win32.h done by the `mman-win32-1-include_name_change.patch` file stopped being applied albeit was kept in the repository.
> mman-win32: re-enable static build after changes in ca5bba6

- src/jsoncpp.mk
These might be useful - Debian installs them by default
> jsoncpp: Build & install cmake files

- src/nsis-1-fixes.patch
- src/nsis.mk
@starius @tonytheodore
I have began porting `nsis` pkg to `x86_64-w64-mingw32` targets.
Most of changes are trivial. But work is not finished yet.
I have stuck on this build failure:
http://www.susepaste.org/view/raw/29773209
Unfortunately, my knowledges of Assembler in a common and for x86 in particular are equal to zero.
Any advices?
Do we really need file `./usr/<target>/share/nsis/Bin/makensisw.exe`?
I have tested `make nsis -k -i` and almost all other files are successfully installed.
Only this binary file and `Contrib/Graphics` files are absent.
> nsis: fix build for x86_64-w64-mingw32 targets

- src/openthreads.mk
openthreads should not do rebuild of osg. it should only build src/OpenThreads
> openthreads: build in  src/OpenThreads

- index.html
- src/glm-test.cpp
- src/glm.mk
This pull request contains build rules for glm 0.9.7.4 (http://glm.g-truc.net/0.9.7/index.html).
glm is a header-only library, so it can be vendored in projects that use it; however, some libraries (e.g. CEGUI 0.8.7) expect to find it in the build environment.
The test program should generate the output
```
mat4x4((0.672222, 0.000000, 0.000000, 0.000000), (0.000000, 0.896295, 0.000000, 0.000000), (0.000000, 0.000000, -0.501001, -0.500000), (0.000000, 0.000000, -0.200200, 0.000000))
```
> glm: add rules to download/build version 0.9.7.4

- plugins/native/gettext.mk
Alternative fix to mxe/mxe#1367 - always use the version of libxml2 included in gettext instead of trying to use the system version
> Always use the included version of libxml

- src/hyperscan-1-fixes.patch
- src/hyperscan.mk
I have tested `i686-w64-mingw32.static` in Windows XP in VirtualBox after disabling AXV2 instructions by specifying `-DCMAKE_C_FLAGS="-march=core2" -DCMAKE_CXX_FLAGS="-march=core2"` to cmake.
Could someone test it in native Windows on machine with AVX2 support, please?
To test, run `test-hyperscan.exe some-pattern some-file`, e.g. `test-hyperscan.exe a C:\boot.ini` and make sure that there are some hits:
```
Match for pattern "a" at offset 57
Match for pattern "a" at offset 69
Match for pattern "a" at offset 82
Match for pattern "a" at offset 93
...
```
To make sure everything works, full test suite can be used. It is not installed to `bin` directory, but it can be extracted from build directory (`tmp-<target>/hyperscan-4.2.0.build/bin/unit-hyperscan.exe`). It requires file …
> Fix hyperscan and update to 4.2.0

- Makefile
When plugins are specified on the command line, automatic native plugins
are not included (currently for darwin and wheezy):
```
$ make gmsl-print-MXE_PLUGIN_DIRS MXE_PLUGIN_DIRS=plugins/apps/
MXE_PLUGIN_DIRS = plugins/apps/
```
See:
https://www.gnu.org/software/make/manual/make.html#Override-Directive
https://github.com/mxe/mxe/issues/1259#issuecomment-217376756
> fix native plugins when additional dirs are specified

- plugins/README.md
Proposed fix for #1364 
This probably should make its way in one form or another to `gh-pages` branch, as well as `MXE_VERBOSE` variable which is extremely useful.
> docs: add mini-tutorial on plugins

- Makefile
- src/mxe-conf.mk
Removing MXE directory with `rm -rf` used to fail on file `usr/readonly/.gitkeep` because directory `usr/readonly` was readonly. Now readonly directory is created in `tmp-*` directory and `.gitkeep` is not created for it (because `tmp-*` is not under `usr/`). Problems with removing MXE directory are fixed even in case of interrupted build.
fix #1221
> create tmp-*/readonly instead of usr/readonly

- patch.mk
winpcap has directory wpcap/libpcap/.git in its source tree. Git considers wpcap/libpcap to be a submodule, which is unwanted.
> patch-tool-mxe: rename existing .git directories

- src/libjpeg-turbo-1-fixes.patch
- src/libjpeg-turbo.mk
> libjpeg-turbo: update from 1.4.1 to 1.5.0

- src/gcc.mk
> Add plugin for compiling mingw-w64 with secure APIs enabled.

- src/qtsystems.mk
The file changed in upstream. The only difference is that top-level directory of the original file is qtproject-qtsystems-4e3a7ed and in new version it is qt-qtsystems-4e3a7ed.
fix #1405
> qtsystems: update checksum

- Makefile
Following https://github.com/mxe/mxe/pull/1415#issuecomment-230095906, note use of lesser-known `make` features.
> Makefile: note use of target-specific variables

- plugins/examples/host-toolchain/README.md
- plugins/examples/host-toolchain/qt5-host-tools.mk
starting point for #950, builds `qmake.exe`, `rcc.exe`, etc
> add qt5-host-tools example plugin

- src/poppler-1-win32.patch
- src/poppler.mk
Tested on `i686-w64-mingw32.shared`. Also related to https://github.com/mxe/mxe/issues/1388
> poppler: enable .dll builds

- src/qt.mk
On OSX, the default mkspec doesn't set `win32-g++` correctly.
The following workarounds are possible:
- set `QMAKESPEC` env var
- use `-spec` command line option
- set `CONFIG+=`
- symlink mkspecs/default
The internal build of qt always seems to use the `-spec` option,
but that doesn't solve the default case - the symlink approach used
on linux appears to always work.
closes #1370
> qt: symlink mkspecs/default

- src/ocaml-camlimages-1-fixes.patch
See: https://github.com/mxe/mxe/pull/1423#issuecomment-233153020
Fixes the build after `giflib` update, but I can't get the current patch to apply with `make import-patch-*` or by hand with `git am`.
> ocaml-camlimages: fix for giflib >=5.1

- index.html
- src/ghostscript-1-fixes.patch
- src/ghostscript-test.c
- src/ghostscript.mk
Since the upstream developers don't seem to care much about supporting MinGW, and especially not about cross-compiling, and since they use a kind of ugly build system, a lot of stuff needed to be patched.
The patch is based on the patches from the [MinGW package](https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-ghostscript), plus it enables cross-compiling.
If this gets merged, [libspectre](https://github.com/darealshinji/mxe/tree/libspectre-new) could be added too, which is a wrapper library for ghostscript.
> New package: ghostscript

- index.html
- src/libspectre-1-fixes.patch
- src/libspectre-test.c
- src/libspectre.mk
libspectre is a wrapper around libgs (ghostscript) and used to read postscript documents.
> New package 'libspectre'

- src/cmake/modules/FindFreetype.cmake
From https://github.com/mxe/mxe/pull/1447#issuecomment-235851175, `cegui` expects `INCLUDE_DIR` instead of `INCLUDE_DIRS`.
> FindFreetype.cmake: add INCLUDE_DIR

- src/qt3d.mk
this is fixing the issue #1462 as proposed by @tonytheodore. Testing was good now.
> fix for #1462 where qt3d failed to build on JOBS := 4

- plugins/luarocks/luarocks-1-fixes.patch
- src/lua.mk
The canonical Lua DLL file name in Windows is either Lua5x.dll or Lua5.x.dll.
> Windows Lua DLLs should not start with "lib"

- plugins/examples/host-toolchain/README.md
- plugins/examples/host-toolchain/gcc-host.mk
- plugins/examples/host-toolchain/qt5-host-tools.mk
- plugins/examples/host-toolchain/winpthreads-host.mk
add winpthreads until gcc is built once per arch #1019
fixes #950
> host-toolchain plugin: fix shared libgcc and qt tools

- Makefile
- index.html
This is very handy for testing against a local repo, especially when
upstream changes are happening quickly.
See also #183
> Makefile: enable local $(PKG)_SOURCE_TREE

- src/glm.mk
This pull request updates glm to 0.9.7.6 (release notes: http://glm.g-truc.net/0.9.7/updates.html). 
The results of `test-glm.exe` on both `i686-w64-mingw32.shared` and `x86_64-w64-mingw32.shared` are identical to each other and to the 0.9.7.4 release.
> glm: update to version 0.9.7.6

- src/physfs-1-cast-fixes.patch
- src/physfs.mk
This PR contains a patch (submitted to icculus, awaiting feedback) that works around some pointer-to-integer-cast problems.
The resulting x86-64 `test-physfs.exe` produces identical output to the i686 `test-physfs.exe`; furthermore, the application I'm building with PhysicsFS also works properly with the MXE x86-64 physfs build.
The patch was extracted from some fixes I did on the PhysicsFS Mercurial repository, which is why it's in Mercurial format.  (The MXE pipeline can apply it fine, however.)  If desired, I can change it to conform to git patch format.
> physfs: enable x86-64 build

- plugins/gcc6/README.md
- src/upx.mk
See: https://github.com/mxe/mxe/pull/1360/files/3ab014bd5672a1c84c6d93630634a2b79cdb9b8c#r75447401
Tested on OSX clang-700.1.81, gcc6 6.1.0_0, and gcc5 5.4.0_0
> upx: disable -Werror on native builds

- src/cmake-1-fixes.patch
- src/mxe-conf.mk
Windres doesn't recognise various gcc flags like `-mms-bitfields`,
`-fopenmp`, `-mthreads` etc. (basically anything not `-D` or `-I`).
CMake will filter options if `add_compile_options()` is used, but not
for `add_definitions()`. The developers class it as a "won't fix" as
they believe `add_definitions()` shouldn't be used for such flags.
Fixes #1475
> cmake: fix windres invocation

- Makefile
Error message:
$ make update-package-pire
...
bash: -c: line 0: syntax error near unexpected token `|'
...
Overlooked in b52d3c0c9c24e7904908dc50f0c7c6f163556fab
See https://github.com/mxe/mxe/pull/1439
> fix MXE_GET_GITHUB_TAGS

- src/hyperscan-1-fixes.patch
- src/hyperscan.mk
Changelog: https://github.com/01org/hyperscan/releases/tag/v4.3.0
Patch "simplegrep: open file in binary mode" was merged in upstream: https://github.com/01org/hyperscan/pull/26
> hyperscan: update from 4.2.0 to 4.3.0

- src/ragel.mk
tested on OS X with gcc 6.1.0 and clang
fixes #1510
> ragel: fix build with gcc6

- src/hyperscan.mk
Changes: https://github.com/01org/hyperscan/releases/tag/v4.3.1
> hyperscan: update from 4.3.0 to 4.3.1

- src/opencsg-1-fixes.patch
- src/opencsg.mk
Minor but important upgrade fixing an issue on Intel GPU.
This only updates the makefile and resolves the conflicts applying the qmake project file patch.
From http://opencsg.org/news.html:
_On Intel graphics hardware, the new rendering path in the SCS algorithm in OpenCSG 1.4.0 entirely failed to work. This was apparently due to an incompatibility of the fragment program with the fixed function pipeline used at the vertex stage. OpenCSG 1.4.1 implements a workaround: a vertex program is now used instead. I hope that the rendering bugs on Intel graphics hardware are now really a thing of the past._
> opencsg: update to 1.4.1

- .travis.yml
- tools/plugins-with-additional-packages.sh
- tools/s3-fetch-and-sync
List of plugins with additional packages was moved from s3-fetch-and-sync
to plugins-with-additional-packages.sh.
> travis: download packages of plugins as well

- docs/index.html
- plugins/go/go-1-fixes.patch
"Environment variable" is more commonly used.
> s/environmental variable/environment variable/

- docs/index.html
- src/glpk.mk
Replaces #1529.
Builds all four targets successfully on OSX and tested with Win10 x64.
@jweaton, here's a step-by-step:
```
git checkout -b add-glpk
./tools/skeleton.py \
--name glpk \
--file-url https://ftp.gnu.org/gnu/glpk/glpk-4.60.tar.gz \
--description "GNU Linear Programming Kit" \
--website https://www.gnu.org/software/glpk/
git add .
git commit -m'add package glpk'
git commit -a -m'glpk: add deps, test, and updates'
git push tonytheodore add-glpk:add-glpk
```
Next steps after review:
```
git rebase master -i
git push tonytheodore add-glpk:add-glpk -f
```
> add package glpk

- src/cpp-netlib.mk
For find_package(cppnetlib) to work, the directory for the cmake files
must be called the same as the files installed into the directory.
Installing directly into the cmake directory would also be an option...
> Fix cpp-netlib cmake directory.

- src/libgda-1-fixes.patch
Error:
```
make[4]: Entering directory
'mxe/tmp-libgda-i686-w64-mingw32.static/libgda-4.2.13/libgda-ui/demos'
(here=`pwd` ; cd . && perl $here/geninclude.pl basic_form.c data_model_dir.c
form.c form_rw.c form_pict.c form_data_layout.c grid.c grid_rw.c grid_pict.c
grid_data_layout.c linked_grid_form.c linked_model_param.c ddl_queries.c
login.c provider_sel.c tree.c cloud.c combo.c) > demos.h
Can't use 'defined(@array)' (Maybe you should just omit the defined()?)
at mxe/tmp-libgda-i686-w64-mingw32.static/libgda-4.2.13/libgda-ui/demos/geninclude.pl line 43.
Makefile:819: recipe for target 'demos.h' failed
```
Similar to https://github.com/mxe/mxe/issues/1112
Fix https://github.com/mxe/mxe/issues/1524
> libgda: fix build failure on perl v5.22.1

- src/openssl.mk
libgcrypt dependency was added in 9f465ff71479dba32e092581165a2c7256554ac9 by @vog on behalf of @mabrand.
In https://github.com/mxe/mxe/pull/1508#issuecomment-242895809 @tonytheodore said it could be removed.
Tested on i686-w64-mingw32.shared
> openssl: remove libgcrypt dependency

- plugins/luarocks/luarocks.mk
Luarocks wrapper used to keep lock dir not removed if luarocks process failed.
To run it again, the lock directory should have been removed manually.
> luarocks wrapper: remove lock if failed

- tools/skeleton.py
Function os.rename fails if files are in different filesystems, e.g. if /tmp is mounted as tmpfs.
> skeleton.py: use shutil.move instead of os.rename

- src/qt.mk
- src/qtbase.mk
Qt and qtbase fail to build if host compiler is GCC 6 with the following error message:
```
cc1: error: one or more PCH files were found, but they were invalid
cc1: error: use -Winvalid-pch for more information
cc1: fatal error: .obj/release-shared/qt_pch.h: No such file or directory
```
See https://github.com/mxe/mxe/issues/1554
See https://github.com/mxe/mxe/issues/1103
See https://github.com/mxe/mxe/pull/1527#issuecomment-254001204
> qt, qtbase: -no-pch (pre-compiled header support)

- plugins/gcc5/gcc5-overlay.mk
Gcc 5.3 fails to build with gcc 6.
The error message is:
cfns.gperf:101:1: error: ‘const char* libc_name_p(const char*, unsigned int)’ redeclared inline with ‘gnu_inline’ attribute
See https://gcc.gnu.org/bugzilla/show_bug.cgi?id=69959
See https://github.com/mxe/mxe/pull/1527#issuecomment-256273786
> gcc5 plugin: update gcc from 5.3 to 5.4

- Makefile
- src/yasm.mk
They are useful for applying flags only to cross or only to native targets.
> add new variables: BUILD_CROSS, BUILD_NATIVE

- src/liblo.mk
Try to use the latest (really useful) guidelines by @starius (not yet merged). Also allow for shared build, which was previously disabled.
Testing on a fresh MXE, for both shared and static with posix, the result is the following:
```
......................../mxe/usr$ find -name "liblo[\.-]*"
./x86_64-w64-mingw32.shared.posix/bin/liblo-7.dll
./x86_64-w64-mingw32.shared.posix/lib/liblo.dll.a
./x86_64-w64-mingw32.shared.posix/lib/liblo.la
./x86_64-w64-mingw32.shared.posix/lib/pkgconfig/liblo.pc
./x86_64-w64-mingw32.static.posix/lib/liblo.a
./x86_64-w64-mingw32.static.posix/lib/liblo.la
./x86_64-w64-mingw32.static.posix/lib/pkgconfig/liblo.pc
```
Not sure what else is needed. I could try it. :)
> Update liblo version from 0.28rc to 0.28, fix configure and make.

- src/portaudio-1-fixes-crlf.patch
- src/portaudio.mk
I had a little problem at first:
```
$ make portaudio
[using autodetected 2 job(s)]
[check requirements]
Missing requirement: openssl
```
To make it work, I compiled it like this:
make portaudio DONT_CHECK_REQUIREMENTS=1
But I guess this is unrelated to my changes to the PortAudio package.
> Upgrade PortAudio to version 19.6.0

- src/hyperscan.mk
This version of hyperscan adds a fix for boost bug introduced in boost 1.62.0.
See https://github.com/mxe/mxe/pull/1549#issuecomment-255600102
See https://github.com/01org/hyperscan/issues/39#issuecomment-260495946
> update hyperscan to 4.3.2

- src/vmime.mk
This reverts commit 07ffabcf49ff4b17775b59053db35041e8081e5b.
Vmime was broken after this update.
See https://github.com/mxe/mxe/issues/1586
> Revert "vmime: update"

- src/libjpeg-turbo.mk
Tested for:
* x86_64-w64-mingw32.static and x86_64-w64-mingw32.shared targets built with gcc6
* i686-w64-mingw32.static and i686-w64-mingw32.shared targets built with gcc4.9
> libjpeg-turbo: update from 1.5.0 to 1.5.1

- src/crystalhd.mk
Failed download: https://travis-ci.org/mxe/mxe/builds/181565782
http://www.broadcom.com/docs/support/crystalhd/crystalhd_lgpl_includes_v1.zip
does not work anymore.
From https://www.broadcom.com/
> Introducing the New Broadcom Limited Website
> Broadcom and Avago are one company. Now the websites
> are integrated, too. Find all the product information
> you need right here in one place.
one can conclude that the file is not expected to appear there,
so switching to mirror website https://ftp.videolan.org/contrib/crystalhd/
which hosts the same file.
> crystalhd: change download URL to a mirror

- Makefile
```
$ openssl --help
Invalid command '--help'; type "help" for a list.
$ echo $?
1
$ openssl help
...
$ echo $?
0
```
fix https://github.com/mxe/mxe/issues/1593
> fix detection of openssl in Debian Sid

- docs/index.html
The code loading versions from .mk was written before versions cache was added to the repo. See e570f8aae5583d91b1e910f7f0a7a2459fa3d161
Now as versions cache (versions.json) is a part of the repo, this code is not needed.
> index.html: rm JS code loading versions from .mk

- src/libdvdetect.mk
It depends through Requires.private.
Broken build: https://gist.github.com/c1606f613d18fbcdf938941145f5fbbb
> libdvdetect: add dependency on openssl

- src/upx.mk
It fails to build on 32-bit Ubuntu due to attempt to use ASM version.
See http://lists.nongnu.org/archive/html/mingw-cross-env-list/2016-12/msg00000.html
> native upx: disable asm

- src/blas.mk
... while upstream URL is being fixed
See https://github.com/mxe/mxe/issues/1610
It is a workaround.
> download blas from backup

- src/poppler.mk
It used to install files to <target>/share/gtk-doc/html/poppler/
See https://github.com/mxe/mxe/pull/1617
> poppler: disable installation of documentation

- src/gst-libav.mk
gst-libav is required by clementine for playing wma and ape formats.
> add package gst-libav

- plugins/apps/clementine_qt4-1-fixes.patch
- plugins/apps/clementine_qt4.mk
Problems:
1) #1269 #1273
2) (non critical) clementine-1-fixes.patch contain workaround that allow 64-bit build, but if left mouse click on menu "Tools->Vizualizations" it lead to crash:
```
-#  ifdef _WIN64
+#  if defined(_WIN64) && !defined(__MINGW32__)
typedef __int64 ptrdiff_t;
```
3) (non critical) It is not clear how to calculate the only required gstreamer plugins, currently music playback leads to crash. It can be fixed by manually copy all gstreamer plugins to subdirectory "gstreamer-plugins" and also copy all gstreamer plugins to directory with clementine.exe and re-run ./copydlldeps.sh.
4) (non critical) clementine-1-fixes.patch contain fix for detecting pthread:
```
find_library(PTHREAD
-  pthreadGC2
+  pthread
)
```
because `clementine` uses pthreads  POSIX 1003.1-2001 from …
> add package clementine_qt4 to mxe/plugins/apps

- src/gnutls.mk
tests install a dummy libcrypt32 which clobbers the w32api
see: https://github.com/mxe/mxe/pull/1541#issuecomment-273373973
> gnutls: disable tests

- src/liblastfm-1-fixes.patch
- src/liblastfm-test.cpp
- src/liblastfm.mk
Qt5 build.
patch is required to separate headers of lastfm for Qt4 and Qt5 builds.
#1356
Clementine from Debian has used this library.
> add package liblastfm

- src/gcc.mk
This is needed to update glib to 2.51.1. It uses strerror_s,
which is guarded by MINGW_HAS_SECURE_API.
See http://win-builds.org/bugs/index.php?do=details&task_id=79
See https://sourceforge.net/p/tdm-gcc/bugs/305/
> mingw-w64: add --enable-secure-api

- plugins/apps/ricochet.mk
The list of components was deduced from official build instructions:
https://github.com/ricochet-im/ricochet/blob/master/BUILDING.md#fedora
See https://github.com/mxe/mxe/pull/1607#pullrequestreview-19498314
> ricochet depends on specific parts of Qt5, not all

- src/boost-test.cmake
- src/boost-test.cpp
- src/boost.mk
See http://lists.nongnu.org/archive/html/mingw-cross-env-list/2017-02/msg00002.html
Appears to build and run:
> boost: add test for boost.context linking

- Makefile
- README.md
- docs/index.html
- src/apr.mk
- src/gcc.mk
- src/libmysqlclient-1-fixes.patch
See #1411 and #1559 allows variants like:
```
i686-w64-mingw32.static.posix.dw2
i686-w64-mingw32.static.dw2
x86_64-w64-mingw32.shared.win32.sjlj
etc.
```
> allow non-default exception handling targets

- src/qtsparkle-1-fixes.patch
- src/qtsparkle-test.cpp
- src/qtsparkle.mk
- src/qtsparkle_qt4.mk
Qt5 version of qtsparkle are required for https://github.com/clementine-player/Clementine/tree/qt5
Problems with linking for static targets: https://gist.github.com/pavelvat/1497b6ce639ff1f12baaad14c92c2c9a
Previously I fixed similar problem by listing all dependent libraries: https://github.com/eiskaltdcpp/eiskaltdcpp/blob/master/eiskaltdcpp-qt/CMakeLists.txt#L268-L291
Maybe anybody to know how to make universal static build (i.e. for MXE Qt5, for 
mxe/plugins/examples/custom-qt-min, for non MXE Qt5) without listing all dependent libraries in CMakeLists.txt?
> add package qtsparkle (build with Qt5)

- src/glib.mk
Recent versions of glib require libmount on Linux. If it is unavailable,
configure fails with
checking libmount/libmount.h presence... no
checking for libmount/libmount.h... no
configure: error: *** Could not find libmount
This commit disables libmount by patching `--disable-libmount` into the configure command line.
(FYI, the windows build is unaffected because libmount is only enabled by default on Linux.)
> glib 2.50.2 native build fails, libmount dependency missing

- .travis.yml
- src/mxml.mk
Package wxwidgets is downloaded for more than 10 minutes,
Travis failed because of no output for 10 minutes:
https://travis-ci.org/mxe/mxe/builds/205649309
> Travis: print spaces every minute to fix build

- src/curl.mk
- src/libidn2-1-fixes.patch
- src/libidn2-test.c
- src/libidn2.mk
- tools/build-pkg.lua
libidn was not really used by curl:
> checking if idn2_lookup_ul can be linked... no
> checking idn2.h usability... no
> checking idn2.h presence... no
> checking for idn2.h... no
> IDN support:      no      (--with-{libidn2,winidn})
idn2 works:
> checking if idn2_lookup_ul can be linked... yes
> checking idn2.h usability... yes
> checking idn2.h presence... yes
> checking for idn2.h... yes
> IDN support:      enabled (libidn2)
> add libidn2 and use it in curl instead of libidn

- Makefile
Regular downloads of packages are verified by checksums, so
--no-check-certificate doesn't compromise the build system,
but the checksums themselves are often updated with update-checksum-%
which in turn calls the regular package download mechanism, so there
is a possibility of downloading and sealing a poisoned file.
On the one hand, old systems may still rely on --no-check-certificate,
so it is not nice to completely disable it for regular downloads.
However keeping this option enabled for backup servers only is enough
to support such systems because of the fallback mechanism.
On the other hand, download from a backup doesn't make sense while
updating a package, because the package is definetely not in the backup yet.
So --no-check-certificate is now enabled only for backup servers
and …
> disable --no-check-certificate while updating packages

- src/cmake/conf/mxe-conf.cmake.in
- src/cmake/conf/target-cmake.in
The script checks if -DCMAKE_BUILD_TYPE is passed in command line and if
it is not passed, passes -DCMAKE_BUILD_TYPE=Release. So now other build
types are supported, just pass -DCMAKE_BUILD_TYPE=<desired-type> to the
script $(TARGET)-cmake.
> support overriding CMAKE_BUILD_TYPE in cmdline

- src/armadillo.mk
Packages armadillo and gdal (depends on armadillo) tested on all 4 targets.
Fix https://github.com/mxe/mxe/issues/1713
> armadillo: update to 7.800.1

- src/gst-plugins-bad.mk
- src/gst-plugins-good.mk
- src/gst-plugins-ugly.mk
fix for https://github.com/mxe/mxe/issues/1624
https://github.com/mxe/mxe/pull/1684 was splitted on two independent PR due to unresolved problem with high CPU usage with gstreamer 1.10.4.
> add missing gstreamer dependencies

- plugins/native/jessie/gettext.mk
- plugins/native/jessie/libiconv.mk
Fix for https://github.com/mxe/mxe/pull/1718
See https://github.com/mxe/mxe/pull/1695#issuecomment-287574293
> enable native gettext and libiconv on Jessie

- Makefile
- github.mk
- src/assimp.mk
- src/box2d.mk
- src/glfw3.mk
- src/glm.mk
- src/googlemock.mk
- src/googletest.mk
- src/hyperscan.mk
- src/librosco.mk
- src/qtserialport_qt4.mk
> github.mk: fix tag prefix with single `v` and pkg name <> project name

- Makefile
- docs/index.html
Use `.DEFAULT_GOAL` [special variable] instead of `.DEFAULT`
[built-in target] as the latter depends on include order and
can cause confusing behaviour.
`LOCAL_PKG_LIST` was [broken] in #1729 and this allows for any
current `settings.mk` to work correctly. Should also fix #1264
and #1267 since MXE isn't going to include any other files that
set this variable in a surprising way.
[special variable]:https://www.gnu.org/software/make/manual/make.html#Special-Variables
[built-in target]:https://www.gnu.org/software/make/manual/make.html#Special-Targets
[broken]:https://github.com/mxe/mxe/commit/1cf2afb5d3afb1dda0d7a5322be758ec2befd2a1
> Makefile: explicitly set .DEFAULT_GOAL for LOCAL_PKG_LIST

- src/vtk-1-fixes.patch
This small patch fixes compilation of vtk if gcc 6 is installed on the build system.
> vtk: Fix compilation on build systems with gcc 6

- Makefile
It is needed to specify a path to custom wget binary without
removing the argument passed by WGET (--user-agent).
Also can be used to add --no-check-certificate back.
> factor out var WGET_TOOL from WGET

- src/dbus-1-fixes.patch
> dbus: avoid multiple definitions of DllMain in static builds

- src/gendef.mk
gcc 7 has -Wimplicit-fallthrough on by default. On systems where the
build gcc is v7 or newer building gendef will therefore fail with the
following error:
src/gendef.c: In function ‘getMemonic’:
src/gendef.c:1034:15: error: this statement may fall through [-Werror=implicit-fallthrough=]
case c_4: sz++;
Fixes #1786.
> gendef: build with -Wno-implicit-fallthrough

- src/fontconfig.mk
This fixes compilation with gcc >= 6. Actual error message:
```
In file included from fcobjs.c:33:0:
fcobjshash.gperf:172:1: error: conflicting types for 'FcObjectTypeLookup'
```
> fontconfig: update from 2.12.3 to 2.12.4

- src/libidn2.mk
> libidn2.mk: dedup slash after previous commit

- src/qt.mk
This PR is part of splitting #1527 
IIRC this is needed to successfully run `find_package(Qt4)` multiple times
> qt: set CMake QT_QMAKE_EXECUTABLE variable to cache

- src/qtbase.mk
This PR is part of splitting #1527 
As @mabrand said, it would be better to do this by adding a patch to src/qtbase-1-fixes.patch instead of a sed hack.
But I couldn't figure out where to put the dependencies. 
The `lib/cmake/Qt5Module/Qt5ModuleConfig.cmake` file is generated by the `mkspecs/features/data/cmake/Qt5BasicConfig.cmake.in` template file.
This template uses the `CMAKE_INTERFACE_QT5_MODULE_DEPS` variable which is fed by the `mkspecs/features/create_cmake.prf` script.
This script is called from `mkspecs/features/qt_module.prf`
I extracted the dependencies from the pkgconfig-file, which is still generated by qmake not by the prf scripts.
> qtbase: fix CMake static linking dependencies

- tools/copydlldeps.sh
Fixed a small syntax mistake (typo) due to a missing space, and also account for some differences in mac's "find" and "cp".
Fixes #1834
> Fixes for copydlldeps.sh under macOS.

- docs/index.html
- src/binutils-1-fixes.patch
- src/binutils.mk
* fixes original 2.26 regression with iostreams dll
```
$ make gcc STRIP_TOOLCHAIN= MXE_TARGETS=i686-w64-mingw32.shared
[...]
$ i686-w64-mingw32.shared-nm  usr/i686-w64-mingw32.shared/bin/libstdc++-6.dll | grep InitC1
6fefa2d0 T __ZNSt8ios_base4InitC1Ev
```
* replaces #1737
* fixes #1758
* tested on all four targets
WIP pending SOURCE_DATE_EPOCH patch from #1737.
> binutils: update 2.25.1 --> 2.28

- src/openmp-validation-2-perl-cwd-not-in-inc-anymore.patch
Perl v5.26.0 has removed the current directory from the include
path. This breaks the `run_test.pl` script which tries to load modules
from the build directory and fails if the system Perl is 5.26.0 or
newer.
Error message: `Can't locate ompts_parserFunctions.pm in @INC`
> openmp-validation: add current directory to @INC for newer Perl

- src/sdl_sound-1-constant-integer-expression-vs-sign-bit.patch
gcc 6 has added a diagnostic under `-pedantic` that emits a warning
whenever an enumerator value is not a constant integer
expression. This applies to the expression "1 << 31", too, as [1]
explains: that shifts the bit into the sign bit, and therefore it's
not constant.
This warning combined with `-Werror` means that compilation of the
test program fails.
This patch implements the workaround mentioned in [1].
Actual error message:
```
'x86_64-w64-mingw32.static-gcc' -W -Wall -Werror -std=c99 -pedantic '/home/mosu/prog/video/mingw/cross/src/sdl_sound-test.c' -o '/home/mosu/prog/video/mingw/cross/usr/x86_64-w64-mingw32.static/bin/test-sdl_sound.exe' `'x86_64-w64-mingw32.static-pkg-config' SDL_sound --cflags --libs`
In file included from …
```
> sdl_sound: fix test program compilation with gcc >= 6

- src/log4cxx-5-gcc6-fix-narrowing-conversion.patch
g++ 6 is stricter regarding narrowing conversions in initializer
lists. This causes errors similar to the following during compilation
with the gcc6 or gcc7 overlays:
locationinfo.cpp:163:21: error: narrowing conversion of '237'
from 'int' to 'char' inside { } [-Wnarrowing]
This has already been fixed upstream in several consecutive patches,
but there's no release including those fixes yet. This patch consists
of the essence of said fixes.
> log4cxx: fix invalid narrowing conversion tripping up g++ >= 6

- plugins/apps/clementine-1-fixes.patch
- plugins/apps/clementine.mk
required https://github.com/mxe/mxe/pull/1626 (qtsparkle is optional dependency. But required package qttools is listed only in qtsparkle.mk and is not listed in clementine.mk)
problems:
1)build is successful, but crash on launch. For order to workaround it you can copy of settings from clementine-qt4 directory (c:\users\USER_NAME\\.config\Clementine) to clementine-qt5 (c:\users\USER_NAME\\.config\Clementine-qt5). Other way: use patch from https://github.com/clementine-player/Clementine/issues/5297
2)clementine-qt5 currently doesn't play any music files and radio streams (gstreamer related errors).
> add package clementine to mxe/plugins/apps

- src/cmake-1-fixes.patch
- src/hyperscan.mk
Alternative to #1811, this seems like it should be fixed upstream
in gcc/cmake rather than individual packages
> cmake: add option to disable -isystem

- plugins/apps/clementine_qt4-1-fixes.patch
As it turned out the clementine_qt4 have the same problem that Qt5 version of clementine (launch with clean settings) https://github.com/clementine-player/Clementine/issues/5297, https://github.com/clementine-player/Clementine/pull/5669, #1630 :
```1)build is successful, but crash on launch.```
> fix launch clementine_qt4 with clean settings

- src/freetype-bootstrap.mk
- src/freetype.mk
This makes the harfbuzz support explicit: freetype-bootstrap does not
use harfbuzz, but freetype does.
This is inspired by a build error where I had a leftover pkgconfig file from harfbuzz, so freetype-bootstrap target was configured WITH harfbuzz, but failed the compile. Normally, this should not happen, but this makes the build a bit more reproducible - freetype-bootstrap always builds without harfbuzz, freetype always with.
> freetype: Don't autodetect harfbuzz.

- src/devil-1-fixes.patch
- src/devil.mk
Can't figure out why the other two *.rc files patch correctly and
this one doesn't. Patch was created with `make export-patch-` with git
config `autocrlf = input`. Devil has it's own `.gitattributes` file
but nothing seems to work.
fixes #1856
Anyone have some pointers?
> devil: use $(SED) instead of patch for EOL issues

- src/hamlib.mk
updating the package
adjusted lusb-1.0 to make the example compile with all 4 compilers (64bit required the lusb-1.0)
compiled and tested running debian 8 + ubuntu
> updating to hamlib 3.1 + adding lusb-1.0 to pkgconfig

- src/gumbo-test.c
- src/gumbo.mk
This PR adds a package file for [Gumbo](https://github.com/google/gumbo-parser), an HTML5 parsing library.  I have been able to compile Gumbo using this package file with the configuration
```
MXE_TARGETS := i686-w64-mingw32.shared.posix x86_64-w64-mingw32.shared.posix i686-w64-mingw32.static x86_64-w64-mingw32.static
MXE_PLUGIN_DIRS := plugins/gcc6
mingw-w64-headers_CONFIGURE_OPTS =: --enable-secure-api
```
Build checklist:
✔ install .pc file
✔ install bin/test-pkg.exe compiled with flags by pkg-config
✔ install .dll to bin/ and .a, .dll.a to lib
(N/A) use $(TARGET)-cmake instead of cmake
✔ build in `$(BUILD_DIR)` instead of `$(SOURCE_DIR)`
✔ do not run target executables with Wine
(? [1]) do not download anything while building
✔ do not install documentation
✔ do not install .exe files …
> Add package file for Gumbo, an HTML5 parsing library

- src/libarchive-1-fixes.patch
- src/libarchive-test.c
- src/libarchive.mk
> libarchive: use nettle instead of bcrypt for CNG(Crypto Next Generation)

- src/protobuf.mk
It seems that the maintainer remove the 3.3.2 version files from their website. The new version can be compiled successfully.
fixes https://github.com/mxe/mxe/issues/1894 (added by @starius)
> fix protobuf url error

- Makefile
- src/blas.mk
- src/libshout.mk
- src/libssh2.mk
- src/llvm.mk
- src/log4cxx.mk
- src/pcre.mk
- src/pcre2.mk
- src/vtk.mk
* change `libssh2`/`apache`/`xiph` URLs to canonical ones
* resubmit patch to remove unnecessary
`--no-check-certificate` option. The URLs
are non-HTTPS anyway
* restore URL for `blas`, it's working again
> secure/update URLs

- tools/build-pkg.lua
The following files are installed by both cmake-conf and mxe-conf:
usr/i686-w64-mingw32.shared/installed/.gitkeep
usr/i686-w64-mingw32.static/installed/.gitkeep
usr/x86_64-unknown-linux-gnu/installed/.gitkeep
usr/x86_64-unknown-linux-gnu/lib/.gitkeep
usr/x86_64-w64-mingw32.shared/installed/.gitkeep
usr/x86_64-w64-mingw32.static/installed/.gitkeep
In all cases a package installs other files to the same library, so these
.gitkeep files can be safely added to the blacklist.
See https://github.com/mxe/mxe/issues/1886#issuecomment-331719282
> build-pkg: blacklist {installed,lib}/.gitkeep

- src/qt.mk
The xmlpatterns module is disabled by qt4 configure by default.
> compile qt4 with xmlpatterns module

- src/gcc-1-fixes.patch
- src/gcc.mk
From: https://github.com/gcc-mirror/gcc/commit/8e49ac832c6ef83afa52e59f0e7e0e6151f5bd3d
Fixes part of #1913
> gcc: fix Darwin build with Xcode9

- plugins/examples/qt5-freeze/qt5.mk
- src/qt5.mk
fixes #1901
```
$ make gmsl-print-qt5_DEPS
qt5_DEPS = qt3d qtbase qtactiveqt qtcanvas3d qtcharts qtconnectivity qtdatavis3d qtdeclarative qtgamepad qtgraphicaleffects qtimageformats qtlocation qtmultimedia qtpurchasing qtquickcontrols qtquickcontrols2 qtscript qtscxml qtsensors qtserialbus qtserialport qtspeech qtsvg qttools qttranslations qtvirtualkeyboard qtwebchannel qtwebkit qtwebsockets qtwebview qtwinextras qtxmlpatterns
$ make gmsl-print-qt5_DEPS MXE_PLUGIN_DIRS=plugins/examples/qt5-freeze/
qt5_DEPS = qt3d qtbase qtactiveqt qtcanvas3d qtcharts qtconnectivity qtdatavis3d qtdeclarative-render2d qtdeclarative qtgamepad qtgraphicaleffects qtimageformats qtlocation qtmultimedia qtpurchasing qtquickcontrols qtquickcontrols2 qtscript qtscxml qtsensors qtserialbus qtserialport qtsvg …
```
> qt5: read deps from files in current directory

- plugins/gcc6/gcc6-overlay.mk
- plugins/gcc6/gcc6.patch
- plugins/gcc7/gcc7-overlay.mk
- plugins/gcc7/gcc7.patch
From https://github.com/mxe/mxe/commit/9eb13fc4b8ae7a97f3d3b11ddc2f58a79994dd54#commitcomment-24681487,
the patch in #1915 is a backport and doesn't apply to gcc > 5.
> gcc plugins: use plugin-specific patches

- plugins/tcl.tk/tcl.mk
- plugins/tcl.tk/tk.mk
Users of this plugin probably want a full install and newer autotools treat unrecognized options as warnings
> tck.tk plugin: use new style options, full install, and fix build

- plugins/tcl.tk/tcl.mk
- src/sqlcipher-1-fixes.patch
- src/sqlcipher.mk
- src/tcl.mk
Closes #1911.
Installs the executable since that falls into the (small) class of utilities that help developers. The `tcl` bindings can remain disabled until someone investigates what's needed.
@aquiles2k @starius, open issues:
- requires `tcl` to build - should we do a native build or add it to requirements?
- test program appears to be simply an `sqlite` test - I couldn't find any minimal examples of usage for a test case.
> Add package sqlcipher

- Makefile
> Makefile: strip dot from $PATH

- src/vtk.mk
OpenGL/Mesa libs aren't required for compile tools
> vtk: fix native build on headless server

- src/dbus-1-fixes.patch
no `-e` option to `echo`, should be portable
> dbus: fix darwin build

- src/libssh.mk
See GPL and OpenSSL in:
http://mxe.cc/#potential-legal-issues
and:
https://www.libssh.org/archive/libssh/2017-10/0000017.html
> libssh: use libgcrypt instead of openssl

- src/gtk2.mk
- src/gtk3.mk
- src/hdf-eos2.mk
- src/id3lib.mk
- src/pdcurses.mk
- tools/build-pkg.lua
When `waf` executes, it creates a cache directory in:
`./usr/$(BUILD)/bin/.waf-<version>-<checksum>`
This causes conflicting files in `build-pkg` (see #1840) and should
be blacklisted.
> fix various package conflicts

- src/quazip-1-generate-pkg-config.patch
- src/quazip-2-link-to-lz.patch
- src/quazip-3-windows_h.patch
- src/quazip-test.cpp
- src/quazip.mk
Continuing from #1176, cleaned up and added the requested fixes. If you spot anything further issue, please let me know. 
2 out of the 3 patches are sent to upstream, the one which adds explicit link to -lz is MXE specific, as the user free to link to other zip implementation as well (see https://sourceforge.net/p/quazip/patches/27/#6698 )
> add new package: quazip

- Makefile
- tools/s3-fetch-and-sync
There are various cases where a download succeeds but the checksum
is wrong:
- upstream re-releases tarball without new version
- sourceforge returns 200 with a text message about outage
- other strange glitches
In these cases, we currently fail and stop the build. This PR allows
for falling through the next URLs until it will eventually get to
the checksum-suffixed version.
This ensures builds are always (potentially) repeatable as the checksum
associated with the version is reachable. Next step would be to change
all the backups to use suffixed tarballs.
> Makefile: try next download url on failed checksum

- Makefile
LOOKUP_PKG_RULE is called many times and spends a lot of time searching
for rules when the default rule is the most common. This simply
avoids exhaustive searching since we can determine beforehand if there
are multiple rules.
Also drops some of the gmsl functions if favour of normal make
variables.
First commit adds sort/strip so print-deps-for-build-pkg output can be
easily compared.
```
$ git checkout HEAD~1
$ time make print-deps-for-build-pkg \
MXE_TARGETS="`echo {i686-w64-mingw32,x86_64-w64-mingw32}.{static,shared}`"> orig
real	0m17.564s
user	0m16.410s
sys	0m0.783s
$ git checkout speedup
$ time make print-deps-for-build-pkg \
MXE_TARGETS="`echo {i686-w64-mingw32,x86_64-w64-mingw32}.{static,shared}`"> new
real	0m4.036s
user	0m3.624s
sys	0m0.326s
$ diff -u orig new
$
```
> Makefile: speedup LOOKUP_PKG_RULE

- src/gdal-1-fixes.patch
Nice:
```
make init-git-gdal
make import-patch-gdal
cd gits/gdal-2.2.2/
curl 'https://trac.osgeo.org/gdal/changeset/40330?format=diff' | patch -p4
git commit -a -m'Add support for openjpeg 2.3
>
> taken from:
> https://trac.osgeo.org/gdal/changeset/40330'
cd ../..
make export-patch-gdal
```
> gdal: add support for openjpeg 2.3

- plugins/meson-wrapper/conf/mxe-crossfile.meson.in
- plugins/meson-wrapper/conf/target-meson.in
- plugins/meson-wrapper/meson-wrapper.mk
This plugin adds a "meson-wrapper" package, which installs Meson cross files and wrapper scripts for each target, similar to "cmake-conf". This allows Meson projects to seamlessly integrate with MXE.
The wrapper scripts require Meson to be installed on the host system.
Example usage:
```sh
x86_64-w64-mingw32.static-meson sourcedir destdir
```
> Add meson-wrapper plugin

- src/hyperscan.mk
> hyperscan: fix build where native SSSE3 detection fails

- src/winpcap.mk
Not all files mentioned in create_include.bat were installed. This caused build errors in basically all programs which were using winpcap.
Fixes #1389
Fixes #2004
> winpcap: Fix installation of header files

- src/poppler.mk
Make poppler's Qt5 bindings compile by adding the Qt5 tools to $PATH, and use C++11 since the Qt5 header files require it now.
> Fix poppler Qt5 bindings

- src/sdl2-1-fixes.patch
The patch in question is supposed to disable dinput support, but in fact, it doesn't seem to do anything anymore. According to the logs, SDL2 successfully builds with dinput support, with or without the patch, and it works correctly too.
> sdl2: remove obsolete patch

- plugins/qt4/qt4-overlay.mk
- src/openscenegraph.mk
This patch makes openscenegraph build with qt5 (to match what some other libraries such as poppler are building with), and updates the qt4 overlay to include poppler and openscenegraph in that list. The qt5 build has been tested on the x86_64-w64-mingw32.static target.
> Update source files fot qt5, and update qt4 overlays.

- src/sdl_mixer-2-fix-static-ogg-detection.patch
Due to a autoconf error, SDL_mixer 1.2.12 does not correctly detect the OGG Vorbis library when using BUILD_STATIC. This was probably missed because normally SDL_Mixer is built using shared libraries instead, and wasn't fixed until SDL_mixer 2.0.
However, since static building is the default for mxe, I thought it was important to carry this configuration fix over to the old version.
> Fix OGG not working in SDL_mixer 1.2.12

- src/nsis.mk
Fixes #1354 
When building for x86_64-w64-mingw32, set target and default target to AMD64,
> nsis: Set target type to AMD64 when compiling for x86_64-w64-mingw32

- src/boost.mk
- src/pe-parse-1-fixes.patch
- src/pe-parse.mk
- src/pe-util.mk
See: https://github.com/gsauthof/pe-util
Alternative to tools/copydlldeps* with prefixed wrapper that simply prints to stdout so you can pipe to `xargs` etc.
```
$ x86_64-w64-mingw32.shared-peldd \
usr/x86_64-w64-mingw32.shared/qt5/bin/Qt5Network.dll \
--path usr/x86_64-w64-mingw32.shared/qt5/bin/ \
-a \
--ignore-errors
Could not resolve: CRYPT32.dll
Could not resolve: DNSAPI.dll
Could not resolve: IPHLPAPI.DLL
Could not resolve: NETAPI32.dll
Could not resolve: USERENV.dll
Could not resolve: VERSION.dll
/Users/tonyt/dev/mxe/usr/x86_64-w64-mingw32.shared/bin/libcrypto-1_1-x64.dll
/Users/tonyt/dev/mxe/usr/x86_64-w64-mingw32.shared/bin/libgcc_s_seh-1.dll
/Users/tonyt/dev/mxe/usr/x86_64-w64-mingw32.shared/bin/libpcre2-16-0.dll
/Users/tonyt/dev/mxe/usr/x86_64-w64-mingw32.shared/bin/libssl-1_1-x …
```
> add peldd utility

- src/qtnetworkauth.mk
I followed the qwebsockets module closely, so this package should conform to all existing standards. It has also been tested to build against our software and is a simple extension to include the networkauth Qt package that is fairly new-ish as it's existed since Qt 5.8.
> added package for Qt networkauth module

- src/openjpeg.mk
Running the native cmake automatically enables `BUILD_PKGCONFIG_FILES` but the cross-toolchain wrapper disables it.
Related to https://github.com/mxe/mxe/issues/1446
> openjpeg: explicitly enable pkg-config files

- src/libechonest-1-fixes.patch
- Change qt5_use_modules to target_link_libraries
- Change "ENDIF (NOT WIN32)" to ENDIF (MINGW OR NOT WIN32) from original patch that was broken.
> Fix libechonest compile

- src/ffmpeg.mk
ffmpeg updated to using sdl2 a while ago, but the dependency didn't get changed to that, so ffplay doesn't get compiled anymore. This should fix that.
Edit: Related to (or fixes) https://github.com/mxe/mxe/issues/1802.
> ffmpeg: fix ffplay compilation by changing sdl dependency to sdl2

- src/quazip-1-fixes.patch
- src/quazip.mk
Also rework the patches as some of them was accepted in upstream
in the meantime
Thanks!
> quazip: upgrade to 0.7.5 and to the new Github upstream

- src/lua.mk
Lua executable was built as a file of name `lua` with `.exe` extension into `src` directory, but copy command was pointing 'lua` without `.exe` to copy further. This commit makes it copy `lua.exe` instead of just `lua`.
Log before:
```
bash://PsychoX@PsychoX/mnt/e/Libraries/MXE/mxe
$ make lua
[git-log]   95a75e41 Patched `automake` - avoid deprecated syntax that fail.
[build]       lua                    x86_64-w64-mingw32.static.posix
Failed to build package lua for target x86_64-w64-mingw32.static.posix!
------------------------------------------------------------
(echo 'Name: lua'; echo 'Version: 5.3.3'; echo 'Description: lua'; echo 'Libs: -llua';) > '/mnt/e/Libraries/MXE/mxe/usr/x86_64-w64-mingw32.static.posix/lib/pkgconfig/lua.pc'
cp …
```
> Fixed `lua` copy executable command to source from `.exe`

- src/nsis.mk
new versions of NSIS require XGCC_W32_PREFIX not MINGW_CROSS_PREFIX, see http://nsis.sourceforge.net/Docs/AppendixG.html
Thanks!
> use XGCC_W32_PREFIX for newer nsis

- src/mpc.mk
Updated and fixed version checking for `mpc` library, so its updates and compile now. :F 
Links to downloads expired:
https://gforge.inria.fr/scm/viewvc.php/tags/?root=mpc&sortby=date outdate from 3 years.
https://deb.debian.org/debian/pool/main/m/mpclib/mpclib_ - non existing for now.
Outdated version was causing compilation errors:
https://gist.github.com/PsychoXIVI/8ec2305c44e603d411a0da95e9cbd27a
> mpc: update and fixed version checking

- src/gcc-1-fixes.patch
This repairs an issue with MXE building `gcc` on `ppc64le` systems such as the Talos II by backporting a fix from `gcc` 6.5 ( https://gcc.gnu.org/viewcvs/gcc/branches/gcc-6-branch/libcpp/lex.c?view=log&pathrev=261621 ).
> fix gcc compile error on ppc64le

- src/boost.mk
063cd91e1 made some bigger changes to `boost.mk`.  While the first call to `b2` has `--ignore-site-config`, the second one missed it, breaking compilation under gentoo hosts.
> fix boost build under gentoo host

- src/taglib.mk
I'm updating taglib to the latest git revision because of a bug in the current release 1.11.1 (2 years old) corrupting ogg files, there is also new features such as detecting audio by content.
Also correcting the website url.
> Update taglib to follow github

- src/taglib.mk
This will most likely be the next taglib release, I will switch back from git to normal versioning when it is released. See https://github.com/taglib/taglib/issues/837
> Bump taglib

- src/libcint.mk
Attempt to add libcint, but it doesn't produce a libcint.pc file. Tested i686-w64-mingw32.static and x86_64-w64-mingw32.static targets.
> add package libcint

- mxe.github.mk
- src/fribidi.mk
From: https://github.com/mxe/mxe/commit/ac697f5bac7e7590fe1363d1a52113ae6ba442a9#r31310663
It's not easy to reliably parse/guess the extension for manually
uploaded archives using GitHub releases. Even if the naming convention
matches GitHub's automated rules, there are two problems:
- mxe version may be on the ["next" page](https://github.com/fribidi/fribidi/releases?after=0.19.4)
- using API may hit rate limiting if it's a live check at build time
This adds an "archive extension" variable to `GH_CONF` for the simple
cases where all other naming follows GitHub conventions.
> github release macro: add variable for archive extensions

- src/ghostscript-1-fixes.patch
- src/ghostscript.mk
Update Ghostscript to version 9.26, always hide libgs symbols, use local lcms fork (lcms2mt).
> ghostscript 9.26

- src/libgpg_error.mk
Tested for many targets. See #2259.
> libgpg_error: fix build for non-default targets

- Makefile
- README.md
- docs/index.html
See: https://github.com/mxe/mxe/issues/2258#issuecomment-450441252
> Posix threads

- src/libfcgi-1-fixes.patch
- src/libfcgi-test.cpp
- src/libfcgi.mk
* For *.shared targets all is built fine.
* For *.static targets library is built fine, but there is a problem of linking of test program:
```
'i686-w64-mingw32.static-g++' -W -Wall -Werror -std=c++0x -pedantic '/opt/mxe-master/src/libfcgi-test.cpp' -o '/opt/mxe-master/usr/i686-w64-mingw32.static/bin/test-libfcgi.exe' `'i686-w64-mingw32.static-pkg-config' fcgi --cflags --libs`
/tmp/ccwzI8FC.o:libfcgi-test.cpp:(.text+0x5c): undefined reference to `_imp__FCGI_Accept'
/tmp/ccwzI8FC.o:libfcgi-test.cpp:(.text+0x7f2): undefined reference to `_imp__FCGI_printf'
/tmp/ccwzI8FC.o:libfcgi-test.cpp:(.text+0x80c): undefined reference to `_imp__FCGI_printf'
collect2: error: ld returned 1 exit status
```
And I am failing to understand that is wrong here...
Any help is welcome!
> add package libfcgi

- Makefile
- src/qtifw.mk
From #2285
Build only `gcc` with required native libs:
```
$ make MXE_BUILD_DRY_RUN=1 gcc
== gcc is now a dependency of virtual toolchain package cc
- cc will build gcc, pkgconf, and other core toolchain packages
- please update scripts accordingly (ignore if you are building gcc alone)
[check reqs]
[nonet lib]   /Users/tonyt/dev/mxe/usr/x86_64-apple-darwin18.2.0/lib/nonetwork.dylib
[git-log]   7ce446c6 Update packages.json & build-matrix.html
[dry-run]     mxe-conf               i686-w64-mingw32.static
[dry-run]     binutils               i686-w64-mingw32.static
[dry-run]     mingw-w64              i686-w64-mingw32.static
[dry-run]     mxe-conf               x86_64-apple-darwin18.2.0
[dry-run]     gmp                    x86_64-apple-darwin18.2.0
[dry-run]     isl …
```
> Avoid unnecessary implied native builds

- src/vtk-1-fixes.patch
- src/vtk.mk
I had to switch to VTK's libharu fork, since they added some functionality. 
Build has been tested for `i686-w64-mingw32.static`, `i686-w64-mingw32.static.posix` and `i686-w64-mingw32.shared.posix`.
> update vtk to 8.2

- src/zziplib-2-prefer-win32-mmap.patch
- src/zziplib.mk
This re-enables mmap functionality without triggering the compilation error in issue #1038.
> Enable mmap for zziplib

- src/ghostscript.mk
lcms2mt's symbols clash with those from lcms2
> ghostscript: don't use the local lcms2mt fork

- src/curl.mk
Currently, libcurl is not able to use the SSL certificates from the certificate store in Windows due to the dependency on gnutls. This patch fixes this by switching to Schannel/WinSSL, Windows' native SSL library which has access to the certificate store of the OS.
I originally stumbled across this issue in https://github.com/mxe/mxe/issues/2380.
If you don't want any changes in the current curl.mk package, I'll happily split this into a seperate curl-winssl.mk file.
> curl: switch to winssl/schannel

- src/libmpeg2-1.patch
- src/libmpeg2.mk
This commit adds a package for libmpeg2, a free MPEG-2 decoding library used by various projects. The codebase is quite ancient (last version from 2008), so building with x86_64 needs a patch. The patch was taken from https://wiki.scummvm.org/index.php/Compiling_ScummVM/MinGW#libmpeg2.
> New package: libmpeg2

- src/imagemagick.mk
closes #2335
Builds on all four targets, breaks downstream pkg `cimg`.
> [WIP] imagemagick: switch to GH_CONF and update 6.9.0-0 --> 7.0.8-44

- Makefile
- src/qtifw-1-fixes.patch
- src/qtifw.mk
I switched to the unix-download, hence the changed lineendings in the patch.
The unix-download is a tar archive with a false tar.gz file suffix, so I had to change the filename and enable tar archives in mxe.
This package will now create an example installer as test executable.
> qtifw: update and build test

- src/glib-networking.mk
Newer versions of glib-networking would require complete meson build system support as autotools has been dropped.
> Add glib-networking package

- Makefile
The default timeout for wget is 15 minutes.
It's pretty annoying having to wait 15 minutes for make update to continue for each update where the site is actually down.
Right now that's the case for wavpack.
This sets the timeout to 6 seconds and tries to 2, so it doesn't try more than 2 times.
> Set tries and timeout for wget

- src/fluidsynth.mk
This patch updates Fluidsynth to the latest release (2.0.7). I was able to successfully build the package on all supported MXE_TARGETS.
> fluidsynth: Update to version 2.0.7

- src/qca.mk
Tested for:
```
MXE_TARGETS := x86_64-w64-mingw32.shared i686-w64-mingw32.shared
MXE_PLUGIN_DIRS += plugins/gcc9
```
> qca: fix build after recent changes

- src/qtbase.mk
This is a simple edit, I've tested this on my own machine and it works. Without this CMake fails to link executables that require Qt5Network.
> add Qt5Network library dependencies

- src/qtbase-1-fixes.patch
- src/qtbase-test.cmake
- src/qtbase.mk
Couple of changes which makes work at least simple Qt5 applications built with CMake.
One of them is Qt patch I [submitted upstream](https://codereview.qt-project.org/c/qt/qtbase/+/286837).
Fixes #1642
Fixes #2430
Fixes #85
Fixes #2166
> Fix qt5 cmake

- plugins/tcl.tk/tk.mk
Tk needs to be consistent with TCL. Ever since someone added TCL back as a base package, rather than a plugin, the Tk and TCL versions became out of sync. This synchronizes them.
> Make Tk version consistent with Tcl

- src/gcc.mk
The default msvcrt must be the same for ming-w64 headers and crt, so it is better to explicitly set both in the rules file, not just one.
> The default msvcrt must be the same for mingw-w64 headers and crt.

- src/fribidi.mk
Bumping the FriBiDi lib to version 1.0.8.
The latest 1.0.9 archives seems to be broken. The .tar.bz2 archive got removed, the .tar.xz seems to be corrupt and the .tar.gz and .zip archives seem to be incomplete. I'll try to contact the author, so we might be able to get an updated build.
For now, this is as current as we can get :)
> fribidi: bump to version 1.0.8

- src/glib-2-fixes.patch
- src/vtk-2-fixes.patch
- src/vtk-3-fixes.patch
Please pull in these minor changes that allow compilation with gcc-10.1 of the versions of glib and VTK that are presently shipped with MXE. The additional patches of those sources are already in upstream glib (backpport to 2.64 available) and VTK (not released yet, AFAICS). Both changes have been tested locally with gcc-5.5 and 10.1 (shared builds).
See:
* https://gitlab.gnome.org/GNOME/glib/-/merge_requests/1428
* https://gitlab.kitware.com/vtk/vtk/issues/17774
> Trivial patches (glib, VTK) that allow shared compilation with gcc-10.1

- src/vtk-1-fixes.patch
(A small follow up on (completed) pull request #2506)
In a small part of the patch that is now in MXE, somehow the line
numbers got messed up. The result is that the XMLPUBVAR is now
fixed for the cygwin case, not for mingw. This patch fixes that. It adds
'extern' to the __declspec(dllexport) definition of XMLPUBVAR.
The result is what is also in upstream libxml2, and in the
stand-alone version that is shipped with mxe. For details, see:
https://github.com/GNOME/libxml2/commit/1eabc31401b7b8c3b5273993778f37eeef37a055
Please merge this fix. And sorry for the inconvenience.
> VTK+gcc-10.1 fix: XMLPUBVAR: patch the mingw block, not the cygwin

- src/adwaita-icon-theme.mk
GTK3 apps require this package for e.g. window titlebar icons and menu entries.
> Add adwaita-icon-theme

- src/gdk-pixbuf.mk
GTK3 makes use of svg icons, but required librsvg module cannot be build in static
gdk-pixbuf so allow dynamic modules for shared builds.
> gdk-pixbuf: Enable dynamic modules in shared builds

- Makefile
- plugins/gcc10/gcc10-overlay.mk
- src/gcc.mk
- src/qtbase.mk
- src/zstd.mk
WIP because the gcc detection needs more overrides to actually use zstd.
@mbunkus I'm pretty sure the [qtbase issue](https://github.com/mxe/mxe/issues/2517) can be tested without a full rebuild - those overlay plugins don't use the [undocumented](https://github.com/mxe/mxe/commit/24d37efa5dae04fbe143c33b8c6710a8606c5451#diff-fffe09b3b50640845a354114057e2a80R7) addition of [_FILE_DEPS](https://github.com/mxe/mxe/commit/24d37efa5dae04fbe143c33b8c6710a8606c5451#diff-b67911656ef5d18c4ae36cb6741b7965R528).
> Enable native zstd bins for qtbase and libs for gcc10

- src/libraw-test.cpp
- src/libraw.mk
Let's keep jasper disabled for now, as it produces build errors:
/mnt/Lavoro/mxe/mxe/usr/x86_64-w64-mingw32.shared/include/jasper/jas_math.h:
In function 'bool jas_safe_intfast32_mul(int_fast32_t, int_fast32_t,
int_fast32_t*)':
/mnt/Lavoro/mxe/mxe/usr/x86_64-w64-mingw32.shared/include/jasper/jas_math.h:241:12:
error: 'INT_FAST32_MAX' was not declared in this scope
if (x > INT_FAST32_MAX / y) {
^
It's not a required dependency, but we might want to add it later if
someone asks for it (and can provide a solution).
> Add libraw: library for processing raw image files

- src/sdl2.mk
SDL2 Fails to build when `/bin/sh` is set to `dash`.
> SDL2: Use bash instead of /bin/sh. Fixes #2541

- src/mesa-1-fixes.patch
- src/mesa.mk
- src/qtbase.mk
This is based on the work by @manner82.
With this change we build qtbase with the `--opengl=dynamic` option: that means that Qt uses a fallback logic when looking for the OpenGL libraries:
1) If the system opengl32.dll supports at least OpenGL 2.0, use that; otherwise,
2) If libEGL.dll is present, load it; otherwise,
3) If opengl32sw.dll is present, load it.
This is an improvement over the behaviour we get from the current `--opengl=desktop`, which basically crashes if step 1 is not fulfilled. And while we don't have (yet) a way to produce in MXE the libraries mentioned in steps 2 and 3, they can safely be copied from a Qt Windows installation.
The Mesa package is used to ship the header files needed by qtbase. It also produces an opengl32.dll library which _could_ be used on Windows, but …
> Qt opengl dynamic

- plugins/examples/qt5-freeze/qtimageformats-2.patch
Add missing <math.h> #include. Without this the build fails with:
[...]qjp2handler.cpp:853:86: error: 'pow' was not declared in this scope
Taken from bd76e1080ef7ddbbfe683d6371629aecb02bc9bd.
> plugins/examples/qt5-freeze: Fix qtimageformats build (fixes #2563).

- src/cmake/conf/target-cmake.in
The `--install` command line option behaves similarly to `--build`, so treat it the same way.
> Add detection of --install to cmake wrapper.

- src/expat.mk
Failed to download expat from SourceForge. Add an alternative URL solves the problem.
> URL_2 for expat

- src/libsndfile.mk
The location of release tarballs has moved to Github releases.
> libsndfile: update to version 1.0.30

- tools/nonetwork.c
There's no obvious way to document this upfront since it should only
be used in very rare cases.
see #2590
> nonetwork.c: enable silent mode for scripts reading stderr

- docs/index.html
The shell command
apt-cache search mxe.*sdl_net
has two issues. First, it will lead to wrong results if a file like `mxe.FOOBARsdl_net` happens to exist in the current directory. Second, it will fail in `zsh` which is more strict about failed globs.
The proposed pull request fixes that.
> Quote asterisk in shell command for portability with zsh

- src/vulkan-headers.mk
- src/vulkan-loader.mk
just the headers and loader
the validation layers are not required for release builds that's why I
omitted them
> add vulkan packages

- src/exiv2.mk
The Exiv2 updater didn't work anymore, which is why Exiv2 got stuck at version 0.25.
This pull request fixes the updater, and updates Exiv2 to its latest version 0.27.3.
> Fix exiv2 updating

- src/libgcrypt.mk
> libgcrypt: update to 1.9.3 and fix static linking

- src/boost.mk
GCC 11 complains about -U__STRICT_ANSI__.
usr/lib/gcc/x86_64-w64-mingw32.static/11.1.0/include/c++/\
x86_64-w64-mingw32.static/bits/c++config.h:558:2: \
error: #warning "__STRICT_ANSI__ seems to have been \
undefined; this is not supported" [-Werror=cpp]
558 | #warning "__STRICT_ANSI__ seems to have been undefined; this is not supported"
I don't know if -U__STRICT_ANSI__ is (still) useful here for other compilers.
> boost: GCC 11 build fix

- src/gcc.mk
As of mingw-w64 v9.0.0, `_WIN32_WINNT` is set to Windows 10. Add `--with-default-win32-winnt` to configure for Vista.
Remove duplicate `--with-default-msvcrt=msvcrt`
Fixes #2662
> Add --with-default-win32-winnt=0x0600

- src/gcc-1-fixes.patch
Issue found on Arch Linux (using g++ 11.1.0).
<details>
<summary>Error in build log:</summary>
```log
/tmp/tmp-gcc-i686-w64-mingw32.static/gcc-5.5.0/gcc/reload1.c: In function ‘void init_reload()’:
/tmp/tmp-gcc-i686-w64-mingw32.static/gcc-5.5.0/gcc/reload1.c:115:24: error: use of an operand of type ‘bool’ in ‘operator++’ is forbidden in C++17
115 |   (this_target_reload->x_spill_indirect_levels)
|   ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
/tmp/tmp-gcc-i686-w64-mingw32.static/gcc-5.5.0/gcc/reload1.c:470:7: note: in expansion of macro ‘spill_indirect_levels’
470 |       spill_indirect_levels++;
|       ^~~~~~~~~~~~~~~~~~~~~
/tmp/tmp-gcc-i686-w64-mingw32.static/gcc-5.5.0/gcc/reload1.c: In function ‘void elimination_effects(rtx, machine_mode)’:
```
</details>
> Fix gcc 5 compilation with g++ 11 on host

- src/qtmultimedia-1.patch
Windows Media Foundation plugin is not yet fully available through mingw so we are disabling it. This fixes #2657
> Disable wmf for qtmultimedia

- docs/packages.json
- src/poppler-1-win32.patch
- src/poppler-test.cxx
- src/poppler.mk
Updates poppler to 21.06.1 and fixes some linking errors when using poppler (with updated test case).
> Update poppler to 21.06.1

- src/graphicsmagick-1-fixes.patch
- src/graphicsmagick.mk
The current MXE build of GraphicsMagick is unusable for several reasons.
The attached patch fixes those issues, while also upgrading from 1.3.33 to 1.3.36.
The improved patch is also offered upstream: https://sourceforge.net/p/graphicsmagick/bugs/154/
> Upgrade graphicsmagick from 1.3.33 to 1.3.36

- src/graphicsmagick-1-fixes.patch
- src/graphicsmagick.mk
Currently, on static builds, GraphicsMagick is compiled without TIFF support, as the TIFF check fails:
```
...
checking tiff.h usability... yes
checking tiff.h presence... yes
checking for tiff.h... yes
checking tiffio.h usability... yes
checking tiffio.h presence... yes
checking for tiffio.h... yes
checking for TIFFOpen in -ltiff... no
checking for TIFFClientOpen in -ltiff... no
checking for TIFFIsByteSwapped in -ltiff... no
checking for TIFFReadRGBATile in -ltiff... no
checking for TIFFReadRGBAStrip in -ltiff... no
checking if TIFF package is complete... no -- some components failed test
...
Option            Configure option              Configured value
-----------------------------------------------------------------
Shared libraries  --enable-shared=no            no
Static libraries …
```
> Fix TIFF support of GraphicsMagick

- src/sqlcipher-1-fixes.patch
- src/sqlcipher.mk
Update to latest available sqlcipher version.
Add patch to fix cross building.
This patch also can be used to build sqlite package from "sqlite-src-*.zip" — Snapshot of the complete (raw) source tree for SQLite.
Instead of "sqlite-autoconf-*.tar.gz" —  C source code as an amalgamation.
Add SQLITE_ENABLE_COLUMN_METADATA compile time definition to make available functions
```
sqlite3_column_database_name()
sqlite3_column_database_name16()
sqlite3_column_table_name()
sqlite3_column_table_name16()
sqlite3_column_origin_name()
sqlite3_column_origin_name16()
```
which are used for example in QtSqlite (and based on it QtSqlcipher) plugin.
This CFLAG also declared in sqlite package.
> Update sqlcipher to version 4.4.3

- src/curl.mk
Currently, the curl package specifies `--with-winssl` at configure time. However, in current versions, this got renamed to `--with-schannel` [1]
The old `--with-winssl` parameter is no longing working, which unfortunately currently breaks SSL/TLS support entirely.
[1] https://github.com/curl/curl/blob/master/configure.ac#L146
> curl: build with schannel support

- mxe.patch.mk
`git tag something` will invoke the editor. As the editor is invoked
via `make`, it doesn't have a TTY to display stuff on. In the case of
`vim`, this means `vim` hangs in the background indefinitely, as does
`make` waiting for `vim` to finish. The user has no way to interact
with that editor instance, having to kill it, which in turn causes
`git tag` and ultimately `make` to fail.
Fixes #2739.
> patch-tool-mxe: provide message when calling "git tag"

- src/lld.mk
Links with lld on the host OS. LLD is target-agnostic, so it "just works".
No need to build it separately for each target.
Can be used by passing -fuse-ld=lld to GCC.
> Add a dummy lld package

- src/vtk-2-fixes.patch
When compiling VTK with the gcc11 plugin, I encountered a number of errors, related to importing/exporting symbols from `vtkInformation.h` ('error: function definition XXX is marked dllimport'). A patch that is consistent with one that has been merged in the upstream VTK git repo fixes this problem, and is the subject of this pull request. See the commit log for details.
I am too much an MSW-novice to understand why this problem manifests itself with the gcc11 plugin, but not with the stock gcc or the gcc10 plugin. I checked that the modified sources compile fine with all gcc versions that are offered by MXE (shared builds).
> VTK: Fix dll import/export of vtkInformation.h

- src/libgphoto2-1.patch
- src/libgphoto2-2.patch
- src/libgphoto2-test.c
- src/libgphoto2.mk
The patch libgphoto2-1.patch was PR upstream:
https://github.com/gphoto/libgphoto2/pull/698
Signed-off-by: Jaroslav Škarvada <jskarvad@redhat.com>
Thanks!
> Added libgphoto2

- plugins/gcc10/gcc10-1-driver-access-fix.diff
- plugins/gcc10/gcc10-overlay.mk
This trivial GCC 10 patch fixes the host toolchain to find the driver (cc1, ...). This is originally from Martin Storsjo, added to GCC 11 (https://gcc.gnu.org/pipermail/gcc-patches/2021-April/567815.html), but not GCC 10.
More details: GCC 10 driver is compiled with g++ without-D__USE_MINGW_ACCESS on MinGW. That option is only added to CFLAGS, but not CXXFLAGS. Consequently, the driver will not find executables such as cc1, because access(,X_OK) will always return an error on Windows, as access() on Windows does not check for executability anymore. With __USE_MINGW_ACCESS, MinGW will use its own implementation of access() which for X_OK behaves the same as R_OK.
Reported to GCC via https://gcc.gnu.org/bugzilla/show_bug.cgi?id=101238 and …
> Fix the host GCC to find the driver on MinGW builds

- plugins/windows-xp/gcc-overlay.mk
Since commit 87a9b83dcf7d1650149e1d24f490d70405ddba1f, the minimum version of Windows for standard MXE builds is set to Windows Vista, however a number of libraries (including winpthreads) disable Vista-specific APIs when `_WIN32_WINNT` is defined to a lower version, which makes this useful to have as a plugin.
> Add a plugin for targeting Windows XP

- src/hidapi.mk
The README at https://github.com/libusb/hidapi says "HIDAPI library was originally developed by Alan Ott (signal11). It was moved to libusb/hidapi on June 4th, 2019, in order to merge important bugfixes and continue development of the library." As such, the libusb version is now the official repository and we should use it.
Also update to the latest master. Among other things, this fixes a [bug][autoconf-fix] that broke the build on new versions of autoconf (2.70 and later).
[autoconf-fix]: https://github.com/libusb/hidapi/pull/226
> hidapi: Switch source to new GitHub repo and update

- src/libcomm14cux.mk
This update for libcomm14cux moves to a version that uses the GNUInstallDirs module for CMake to simplify the installation process using standard definitions of install paths.
The test utility is deliberately excluded from the default build (and the MXE build) because it relies on a special piece of FTDI hardware for testing.
> libcomm14cux: Update to 2.1.3

- docs/index.html
Libretro and RetroArch (https://www.retroarch.com/) now switched from Windows/msys2 to Linux/MXE for their Windows builds. Libretro is a huge project, so it's worth putting it on the list.
> docs: add Libretro/Retroarch to "used by"

- src/libsrt.mk
This seems to work pretty well.  Build log:
```
cd '/usr/src/mxe/tmp-libsrt-x86_64-w64-mingw32.static/srt-1.4.2.build_' && x86_64-w64-mingw32.static-cmake '/usr/src/mxe/tmp-libsrt-x86_64-w64-mingw32.static/srt-1.4.2' -DUSE_STATIC_LIBSTDCXX=ON -DIFNEEDED_SRT_LDFLAGS=-lstdc++ -DENABLE_STATIC=ON -DENABLE_SHARED=OFF -DENABLE_EXAMPLES=OFF
== Using MXE wrapper: /usr/src/mxe/usr/bin/x86_64-w64-mingw32.static-cmake
- cmake version 3.17.3
- warnings for unused CMAKE_POLICY_DEFAULT variables can be ignored
== Using MXE toolchain: /usr/src/mxe/usr/x86_64-w64-mingw32.static/share/cmake/mxe-conf.cmake
== Using MXE runresult: /usr/src/mxe/usr/share/cmake/modules/TryRunResults.cmake
== Adding "-DCMAKE_BUILD_TYPE=Release"
loading initial cache file /usr/src/mxe/usr/share/cmake/modules/TryRunResults.cmake …
```
> Add libsrt 1.4.2

- src/openexr.mk
Fixes #2760
Signed-off-by: Jaroslav Škarvada <jskarvad@redhat.com>
> openexr: workaround build error with the gcc-9

- src/ilmbase-1-fixes.patch
This fixes the ilmbase package-- recent build with gcc11 made default gives errors such as:
```
ImathVec.h:795:35: error: ISO C++17 does not allow dynamic exception specifications
795 | Vec3<int>::normalizedExc () const throw (IEX_NAMESPACE::MathExc);
```
This applies patch that removes the throw syntax that is no longer valid past C++17.
> add patch to get ilmbase building under gcc11

- src/wt-1-fixes.patch
* boost problems possibly caused by upgrade to boost 1.78
* need for explicit <limits> likely caused by GCC 11
> Fix boost and gcc11 header issues

- src/icu4c.mk
Remove unnecessary `pe-util` dependency in icu4c package, only causing issues and additional compile time.
Compiled and tested, also works without pe-util dep.
> Remove unnecessary pe-util dependency

- src/harfbuzz.mk
Harfbuzz has built-in Unicode-data functions. Also we do not enabled ICU. So remove extra build dependency. 
Do not waste extra build time.
Build still works fine.
> Remove unnecessary dependency from harfbuzz

- src/llvm-2-fixes.patch
Fix the following build error in llvm under the new gcc11
```
[ 99%] ^[[32mBuilding CXX object utils/benchmark/src/CMakeFiles/benchmark.dir/benchmark_register.cc.obj^[[0m
cd /local2/mxe/tmp-llvm-x86_64-w64-mingw32.shared.posix/llvm-10.0.0.src.build_/utils/benchmark/src && /local2/mxe/usr/bin/x86_64-w64-mingw32.shared.posix-g++ -DHAVE_STD_REGEX -DHAVE_STEADY_CLOCK -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__\
\
STDC_LIMIT_MACROS -Dbenchmark_EXPORTS @CMakeFiles/benchmark.dir/includes_CXX.rsp -Wa,-mbig-obj -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-un\
\
initialized -Wno-class-memaccess -Wno-redundant-move -Wno-noexcept-type …
```
> add patch to fix llvm build under gcc11

- src/qt/qt6/qt6-qt5compat.mk
- src/qt/qt6/qt6-qtdeclarative.mk
- src/qt/qt6/qt6-qtshadertools.mk
- src/qt/qt6/qt6-qttools.mk
Add several Qt6 modules (required to build [TeXworks](https://github.com/TeXworks/texworks/)). Dependencies (in particular for host-builds) might be reducible further, however host builds are required (where added as dependencies) to build native tools and create `Qt6<module>Tools` CMake targets required by dependent packages.
Tested so far only with the `i686-w64-mingw32.static` target on `x86_64-pc-linux-gnu`.
> Qt6 improvements

- src/qt/qt6/qt6-conf.mk
- src/qt/qt6/qt6-qt5compat.mk
- src/qt/qt6/qt6-qtcharts.mk
- src/qt/qt6/qt6-qtdeclarative.mk
- src/qt/qt6/qt6-qtimageformats.mk
- src/qt/qt6/qt6-qtserialport.mk
- src/qt/qt6/qt6-qtshadertools.mk
- src/qt/qt6/qt6-qtsvg.mk
- src/qt/qt6/qt6-qttools.mk
All Qt6 Makefiles that depend on `QT6_METADATA` need to include `qt6-conf.mk` (instead of relying on `make` to automatically parse it first). In turn, `qt6-conf.mk` depends on `qt6-qtbase.mk` for some of its variable assignments.
For make < 4.3, this is essential as those versions don't sort globbing results alphabetically (see #2796 and [make bug 52076](https://savannah.gnu.org/bugs/?52076)). For later versions of make, globbing results are sorted, but still some package names (e.g., `qt6-qt5compat`) would require special treatment as they are sorted before `qt6-qtbase` (which includes some required variables).
Caveats of this patch: it results in `qt6-conf.mk` (and in turn `qt6-qtbase.mk`) being parsed multiple times when running make. However, IMO, this is still the most reliable way …
> Qt6: properly include conf Makefile

- src/gcc.mk
The recent update of jasper requires at least 0x0601, and the current
default of 0x0600 breaks linking everything that uses jasper, including
Qt.
Since there is a good chance other packages will require newer Windows
APIs in the forseeable future (or already do) changing the default to
Win 7 seems like a reasonable step.
Fixes #2771, #2777.
---
The mentioned bugs have been fixed in the meantime in bb65d2c7fa4cebb3a4d1f4fa2b310dc0aa1d7d69 by changing the API for jasper only, but it might be worthwhile considering to generally update the default API given the age of Vista / 7.
> Update default windows API to 0x0601 (Win 7).

- src/qt/qt6/qt6-qtbase.mk
The Qt6 cross-build uses tools from the host build and thus depends on it. CMake configuration of target projects fails if the path to the Qt host build is missing. This pull requests adds a Qt6 package configuration for the CMake target build.
Refers to #2799.
> qt6-qtbase: Add CMake package configuration for Qt6 host path

- src/qt/qt6/qt6-qttranslations.mk
This adds the Qt6 equivalent of `qttranslations`. Programs might want to ship Qt's own translation files so that standard dialogs are translated, too, not just an application's custom dialogs.
> Qt6: add qttranslations

- src/qt/qt6/qt6-qtmultimedia-1-fixes.patch
- src/qt/qt6/qt6-qtmultimedia.mk
Modeled on qt6-qtimageformats. Patch done via `patch-tool-mxe`. Tested with my own MKVToolNix: successful audio playback on Windows.
The patch is needed as the library & include file names are all over the place:
* libraries are all lowercase in the file system, but the `cmake` snippet tries to find them in mixed case
* several includes that are all lowercase in the file system are spelled in mixed case
* the `QtCore` include sub-directory is misspelled `qtcore`
> Qt6: add qtmultimedia

- src/qt/qt6/qt6-qtmultimedia.mk
This forces gstreamer detection off. Otherwise cmake will complain
that EGL isn't found.
> Qt6 qtmultimedia: fix compilation if gstreamer is installed

- Makefile
- src/ccache.mk
In light of what is discussed in #2462, it seems reasonable to allow
having `ccache` put its cache to a persistent storage that is shared
through pipeline runs.  The current setup doesn't do that since it puts
the cache in `MXE_CCACHE_DIR`, a directory in which also binaries and
other files reside that should not be shared as such.
> Allow separating ccache's cache dir to a different

- Makefile
- tools/build-pkg.lua
This patch introduces MXE_PREFIX variable for use at the make command line. PREFIX variable may clash with external software, such as zstd.
To demonstrate the problem, run
```
make -j MXE_PLUGIN_DIRS=plugins/gcc10 MXE_TARGETS=x86_64-w64-mingw32.static.posix PREFIX=`pwd`/usr4 gcc
```
which fails with
```
Failed to build package gcc for target x86_64-w64-mingw32.static.posix!
------------------------------------------------------------
checking for zstd.h... no
configure: error: Unable to find zstd.h.  See config.log for details.
```
because `PREFIX` passed to make on command line gets inherited also in make files of zstd, and consequently `zstd.h` will be installed to wrong directory.
With the patch applied, this works:
```
make -j MXE_PLUGIN_DIRS=plugins/gcc10 …
```
> Introduce MXE_PREFIX for use on make command line (PREFIX does not work)

- plugins/examples/host-toolchain/README.md
- plugins/examples/host-toolchain/cmake-host.mk
- src/cmake-2-install-locations.patch
- src/cmake-3-default-generator.patch
This pull request includes small fixes needed to make the host "cmake" work without a wrapper or overrides. It fixes cmake-host to take into account cmake patches and adds two. One patch changes the default generator to "Unix Makefiles", so that it can be used with the host toolchain built by MXE by default. The other patch fixes host cmake installation location so that cmake finds its own files. Without that patch, one gets
```
$ cmake --version
CMake Error: Could not find CMAKE_ROOT !!!
CMake has most likely not been installed correctly.
```
The two patches are based on Msys2 (0003-Fix-install-destinations.patch is re-used, 0005-Default-to-ninja-generator.patch was updated for a different default).
> Improve host build of cmake (fix install locations, default to Unix Makefiles)

- src/gdk-pixbuf.mk
This ensures that in a static build, all loaders are built in. 
Without this patch, these DLLs for most loaders are created (in a static build):
```
./usr/i686-w64-mingw32.static/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-xpm.dll
./usr/i686-w64-mingw32.static/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-pnm.dll
./usr/i686-w64-mingw32.static/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-bmp.dll
./usr/i686-w64-mingw32.static/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-ico.dll
./usr/i686-w64-mingw32.static/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-gif.dll
./usr/i686-w64-mingw32.static/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-tiff.dll
./usr/i686-w64-mingw32.static/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-tga.dll …
```
> gdk-pixbuf: include all loaders when building statically (rather than creating DLLs)

- src/cfitsio.mk
A description seems to be required when using a newer pkg-config (and does no harm with the one used currently by MXE).
With pkg-config 1.8.0 and without this fix, I get this error during cfitsio build, when it is linking the test:
```
Package cfitsio was not found in the pkg-config search path.
Perhaps you should add the directory containing `cfitsio.pc'
to the PKG_CONFIG_PATH environment variable
```
> cfitsio: include description when generating .pc file

- src/libzmq.mk
libzmq cannot be built because of errors like this:
```
tmp-libzmq-i686-w64-mingw32.static/zeromq-libzmq-c89390f/src/ipc_address.hpp:40:10: fatal error: sys/socket.h: No such file or directory
40 | #include <sys/socket.h>
|          ^~~~~~~~~~~~~~
```
This patch simply disables IPC to make it build, but, there may be a better way (?epoll poller).
> libzmq: disable IPC to allow building.

- src/gcc.mk
This makes the C++ library use clock_gettime and hence more precise timers. Without this setting, system_clock from <chrono> only uses gettimeofday. Msys2 enables the precise timers as well in their builds.
> gcc: enable precise timers (clock_gettime) in the C++ library

- src/boost.mk
Boost 1.78.0 includes accidentally file "collection_size_type copy.hpp", which is not needed but has a space in its name, which may cause trouble for further processing. This patch deletes it.
https://github.com/boostorg/serialization/commit/07c99b8649d7bb900271ca93ba3eea9dcb478f42#diff-c7259865ae65dd94c715482e2abf4fbb3ee9f77e63eb1b6677eada21bd239b08
> boost: remove file accidentally included in boost release (with space in its name)

- src/libffi.mk
This upgrades libffi to version 3.3. This is the most recent version available at https://sourceware.org/pub/libffi/, but there is also version 3.4.2 at https://github.com/libffi/libffi and https://github.com/atgreen/libffi.
> libffi: upgrade to version 3.3

- src/glib.mk
- src/gtk2.mk
This fixes the build of gtk2 (missing -luuid in glib pkg-config file caused linking errors, use of deprecated declarations caused compile error of the gtk2 test).
> Fix gtk2 build

- src/sox-1-fixes.patch
sox uses undocumented platform-specific ways to rewind a pipe and uses it to detect file type on the pipe. However, UCRT is not supported and compilation fails, because sox incorrectly assumes that the FILE structure has element named _base.
This patch does two trivial things to help building for UCRT. It makes the code aware that the _base element is not available. Then, as intended, sox compilation would fail with an error asking to add pipe rewind code on this platform, or to build with NO_REWIND_PIPE defined. This patch also makes it possible to use -DNO_REWIND_PIPE via CFLAGS to build for UCRT without this feature.
> sox: allow building with -DNO_REWIND_PIPE for UCRT

- src/boost-1-fixes.patch
Upstream PR: https://github.com/boostorg/container/pull/222
Example:
```
boost::container::list<std::pair<int, int>> list;
```
```
.../boost/container/allocator_traits.hpp:403:11: error: invalid use of
incomplete type 'struct boost::container::dtl::pair<int, int>'
403 |    {  p->~T(); (void)p;  }
|       ~~~~^
In file included from .../boost/container/detail/node_alloc_holder.hpp:39,
from .../boost/container/list.hpp:34:
.../boost/container/detail/is_pair.hpp:59:8: note: declaration of 'struct boost::container::dtl::pair<int, int>'
59 | struct pair;
|        ^~~~
```
> boost: Fix incomplete type error when using list and pair

- src/chafa.mk
Hi, I've been a happy user of MXE for many years, and today I'm submitting the Chafa library for consideration.
* It's a terminal graphics package not unlike libcaca, but modern and wider in scope (i.e. supports a large number of Unicode symbols and ANSI escape sequence capabilities, sixels, Kitty and iTerm2 graphics extensions).
* It has API to convert pixel buffers into the above formats, generating a stream of terminal sequences and allowing direct manipulation of a character cell-based canvas.
* Platform-wise it depends on GLib and uses many of the same conventions.
* Harfbuzz has an optional dependency on Chafa for the `hb-view` executable.
I've disabled installation of documentation and the command-line executable as per the instructions. Please let me know what you think or if I …
> Add Chafa package

- src/glib-2-link-with-libuuid.patch
- src/glib.mk
The hack to add `-luuid` to the pkgconfig file's `Libs:` field was preventing GLib dependents from building shared libraries with `-no-undefined`, since during the build, libuuid is only available as a static library.
I'm not 100% certain about the fix, since I don't know what the original .pc hack was fixing (commit ee08db3111d1a3388b996991d345926944985856), but a GLib-dependent package I tested with builds fine now with both `x86_64-w64.mingw32.static` and `x86_64-w64.mingw32.shared` targets.
Attn: @kalibera @mabrand
> glib: Move -luuid dependency to Libs.private

- src/qt/qt6/qt6-qtmultimedia-1-fixes.patch
Fixes the following build error:
```
/home/jonas/Projects/jonaski-mxe/tmp-qt6-qtmultimedia-x86_64-w64-mingw32.static/qtmultimedia-everywhere-src-6.4.0/src/plugins/multimedia/ffmpeg/qwindowscamera.cpp:14:10: fatal error: Mfreadwrite.h: No such file or directory
14 | #include <Mfreadwrite.h>
|          ^~~~~~~~~~~~~~~
compilation terminated.
```
> qt6-qtmultimedia: Update patch

- src/qt/qt6/qt6-qtbase.mk
Fixes the following build error on openSUSE:
```
/usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: /__w/jonaski-mxe/jonaski-mxe/usr/x86_64-pc-linux-gnu/lib/libzstd.a(zstd_common.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/lib64/gcc/x86_64-suse-linux/12/../../../../x86_64-suse-linux/bin/ld: failed to set dynamic section sizes: bad value
collect2: error: ld returned 1 exit status
[348/1264] Building C object src/3rdparty/freetype/CMakeFiles/BundledFreetype.dir/src/bdf/bdf.c.o
ninja: build stopped: subcommand failed.
```
> qt6-qtbase: Disable zstd for native build

- src/qt/qt6/qt6-qttools.mk
Building linguist without designer is now possible in Qt 6.4.
> qt6-qttools: Turn off building designer for native build

- src/gst-libav.mk
- src/gst-plugins-bad.mk
- src/gst-plugins-base.mk
- src/gst-plugins-good.mk
- src/gst-plugins-ugly.mk
- src/gstreamer.mk
- gstreamer no longer uses liboil
- some dependencies are moved from bad/ugly to good
> Update gstreamer and fix dependencies

- src/chafa.mk
Fixes: libtool:   error: can't build i686-w64-mingw32.shared shared library unless -no-undefined is specified
> chafa: Add LDFLAGS='-no-undefined'

- src/gdal.mk
Fixes: configure.ac: error: required file 'config.rpath' not found
> gdal: Fix autoreconf

- src/exiv2.mk
With this configuration opetion exiv2 provides a couple of more methods to open image files which take a std::wstring as parameter. This allows supporting file paths containing non-ascii characters.
> exiv2: enable wide string methods

- src/libsndfile-1-fixes.patch
- src/libsndfile.mk
This fixes the libsndfile.pc file by back-porting a trivial fix from upstream libsndfile.
Without the fix, the libsndfile.pc includes an unexpanded variable, and hence sox fails to build with
```
configure: error: cannot find sndfile
```
https://github.com/libsndfile/libsndfile/commit/e4fdaeefddd39bae1db27d48ccb7db7733e0c009
> libsndfile: fix broken libsndfile.pc file (back-port)

- src/libgpg_error.mk
This ensures that gpg-error-config still gets created while building libgpg_error.
Without it, building libassuan fails with 
```
./configure: line 14370: test: : integer expression expected
./configure: line 14377: test: : integer expression expected
checking for GPG Error - version >= 1.17... no
configure: error: libgpg-error was not found
```
> libgpg_error: create gpg-error-config

- src/openssl.mk
Openssl while building static libraries still builds legacy.dll, a loadable module for the legacy driver. This patch ensures that the legacy driver is, instead, compiled into the main static library, following this recommendation:
https://github.com/openssl/openssl/issues/17679#issuecomment-1034949099
> openssl: fix static build to include legacy driver

- src/hunspell.mk
Fixes CVE-2019-16707 among other things (see https://github.com/hunspell/hunspell/releases/tag/v1.7.1)
> Update hunspell to 1.7.1

- src/minizip-1-fixes.patch
- src/minizip.mk
This is a small part of the GDAL 3.6 upgrade (#2918) (@mabrand).
Updating `PROJ` (which is still a todo) causes the `spatialite` build to start failing with the current `minizip`, and upgraded `minizip` to 3.0.1 resolves that.
I am not upgrading further because when I tested 3.0.3 that caused further issues downstream (3.0.2. is where the problem started, I have not looked at later versions yet as they were unreleased when I did this originally).  This will be something to look into once GDAL is upgraded.
I checked all the direct downstream dependencies.  Currently the following fail, but **they also fail on the master branch**, so it is not a change for the worse:
* `cegui` because it's dependency `freeimage` is failing (unrelated to this patch).
* `openscenegraph` shared builds, not …
> update minizip to 3.0.1

- src/mingw-w64-1-fixes.patch
This is a back-port of two patches from mingw-w64 by Martin Storsjo. They redirect access() with UCRT to an internal implementation, which handles X_OK. This is needed for applications which rely on X_OK (not normally supported on Windows).
One of the affected applications is GCC (see https://gcc.gnu.org/bugzilla/show_bug.cgi?id=105506 for details), where unfortunately this problem keeps popping up, last time with GCC 12. The work-around in mingw-w64 should finally resolve it. The symptoms with GCC are that the native compiler (gcc-host) cannot find cc1.
> mingw-w64: backport fix for access() with UCRT

- src/openscenegraph-1-fixes.patch
This is one of the failing revdeps mentioned in #2933.  This was an existing failure where the `tiff` library was not getting properly linked for the shared builds.
> Fix openscenegraph shared builds

- src/poppler-1-win32.patch
- src/poppler.mk
Yet another small change chipped off of #2918.  Declares pkgconfig requires so that static builds relying on pkgconfig work correctly.
> Fix poppler static linking with pkgconfig

- src/hdf4.mk
This is required for correct linking of netcdf once it and hdf5 are upgraded.  Those upgrades are forthcoming, but since this doesn't patch doesn't interfere with anything else splitting it off to make subsequent patches smaller.
This are additional small parts of the GDAL 3.6.0 update #2918.
> add pkgconfig files to HDF4

- Makefile
Sets `wrap-mode` to `nofallback` preventing meson from trying to fetch fallbacks from the net.
> prevent meson from trying to fetch fallbacks over the network

- docs/index.html
Fix #2860
It seems there are packages that require a `python` binary. However, Debian Bullseye no longer packages `python`, only `python2` and `python3`.  By adding `python-is-python3`, we can fix build issues.
> Debian required packages: Add python-is-python3

- src/lua-1-fixes.patch
- src/lua.mk
Please note that `src/lua-1-fixes.patch` had to be changed in a non-trivial way. Lua built fine on my machine, but some more testing (with a clean install and/or on FreeBSD) could be useful.
> lua: update 5.3.3 -> 5.4.4

- src/pkgconf.mk
- src/qt/qt6/qt6-qtbase.mk
- src/qtkeychain-qt6.mk
- src/qtkeychain.mk
QtKeychain (https://github.com/frankosterfeld/qtkeychain/) supports both Qt5 and Qt6. mxe's qtkeychain package only builds for Qt5 today. This Pull Request adds a qtkeychain-qt6 package based on the existing qtkeychain package.
The first two commits solve issues with Qt6's pkgconfig support, which the qtkeychain relies on for its test program.
> Add qtkeychain-qt6 package

- src/spdlog-1-fixes.patch
- src/spdlog-test.cpp
- src/spdlog.mk
upstream: https://github.com/gabime/spdlog
spdlog is a general purpose C++ logging library.
One commit had to be picked from upstream and applied on the latest release to make mingw builds function
https://github.com/gabime/spdlog/commit/da14258533cb951ce85087ceb45556e0b8253660
I didn't end up using patch-tool-mxe and skeleton.py and things appear to be working without issue.
> Add spdlog package

- src/libslirp-1.patch
- src/libslirp-test.c
- src/libslirp.mk
> A general purpose TCP-IP emulator used by virtual machine hypervisors to provide virtual networking services.
[libslirp](https://gitlab.freedesktop.org/slirp/libslirp)
> Add libslirp 4.7.0

- src/netcdf-cxx4.mk
This is another small part of the #2918 (GDAL->3.6.0) upgrade.  It probably should be merged after the #2935 (PROJ) update as that's how I've tested it, but it's likely okay stand-alone.
This is not needed currently and the sole purpose of this patch is to make the final GDAL patch smaller.
> Prepare netcdf-cxx4 for HDF5 upgrade

- src/poppler-qt5.mk
- src/poppler-qt6.mk
- src/poppler.mk
Moving the poppler-qt libraries into their own packages so people don't have to build Qt5 and Qt6 if they just want poppler.
See my request https://github.com/mxe/mxe/issues/2968
Builds on all 4 targets for me.
> poppler: move poppler-qt libraries into their own packages

- src/meson.mk
Tested with all packages that use meson:
export MXE_TARGETS="i686-w64-mingw32.static x86_64-w64-mingw32.shared"
pkgs=$(git grep -l meson src/ | sed -e s%src/%% -e s%\.mk$%% | grep -v meson | grep -v \.patch)
make $pkgs
> meson: update 0.64.1 -> 1.1.0

- docs/index.html
On Ubuntu glib will fail to build if these 2 packages are missing. See the discussion here: https://github.com/mxe/mxe/issues/2875
Apparently missing on Alpine Linux too but I don't know much about its packaging system.
If you add a package, you can …
> Debian: require libpcre3-dev and python3-distutils

- src/sdl2-1-fixes.patch
- src/sdl2.mk
fixes #2983
The patch was rebased against 2.26.2 and, at least as far as I can tell, does what its suppose to.
I've build a few packages that depend on it, but haven't found time to test against any projects.
> sdl2: update to 2.26.2

- src/qt/qt6/qt6-qthttpserver.mk
Add Qt HTTP server module (https://doc.qt.io/qt-6/qthttpserver-index.html) to mxe.
Used the existing qt6-qtsvg and simply changed PKG and CHECKSUM. Compiles in a clean docker container for `x86_64-w64-mingw32.static`.
Once PR #2987 is merged, this module should also depend on QtWebsockets as some optional features require it.
> qt6: Add qthttpserver Qt module

- plugins/examples/host-toolchain/pkgconf-host.mk
This is needed for a static build, otherwise one runs into linking errors such as "undefined reference to `__imp_pkgconf_strlcpy'."
> Fix static build.

- src/freetype-bootstrap.mk
- src/freetype.mk
Freetype by default supports brotli when it finds it installed during the build, so declare a dependency on it to make sure brotli support presence is deterministic in the builds.
> Declare (auto)dependency on brotli.

- src/qt/qt6/qt6-qtscxml.mk
This supersedes #2964, comes in a single commit, and works with the current Qt6 version of MXE (6.6.0).
> Add qt6-qtscxml

- src/mdbtools.mk
mdbtools maintainer and repo changed a while ago. MXE is building old 0.7.1 version which dates back october 2013, and still references older yet Sourceforge repo page.
Current one is  https://github.com/mdbtools/mdbtools.git
This patch should reference correct github repo, and add a temporary fix for the build of v1.0.0. which failed because of deprecation warnings. This warnings have been fixed upstream in dev branch, but not included in a release yet.
* do not run target …
> [mdbtools.mk] Update sources and repo

- src/ccache.mk
This patch fixes the location where MXE puts the cmake user configuration file. The previous location was not correct (anymore?) and the config file there was ignored.
This can be tested via e.g.  `ccache -s`. MXE increases the maximum cache size to 20G from the default 5G. Without this patch, ccache would generate its own configuration file with 5G as the maximum. With this patch, the one from MXE will be used with 20G as maximum. One can also test by putting invalid content, e.g. invalid number as the limit, to the files to confirm where they are read.
> Fix ccache config location.

- src/djvulibre-1-fixes.patch
- src/djvulibre.mk
Also...
- remove dependency on "tiff"; it's not used despite the configure script looking for it
- better way to build static library
- don't export all DLL symbols
- enable pthreads
This will resolve https://github.com/mxe/mxe/issues/3012
PS: upstream discussion about MinGW build compatibility -> https://sourceforge.net/p/djvu/bugs/354/
> djvulibre: fix build failure

- Makefile
When "python" is not installed, PYTHON is empty and the (eager) evaluation of PY_XY_VER causes an error from the shell, which could be rather puzzling. This change  silences such error by not attempting to detect the version of "python" when it is not installed. With "bash", the error is "bash: - : invalid option".
> Avoid python version detection when not installed.

- src/qttools-1-fixes.patch
This PR adds to the patch file `src/qttools-1-fixes.patch` with an extra patch which removes the file `src/assistant/help/Qt5HelpConfigExtras.cmake.in` from `qttools` as it is blocking CMake builds which rely on the `Qt5::Help` module.
These two binaries are used to generate Qt Help Documentation so it serves no use in the context of the cross-compiler. My solution has been to install `qhelpgenerator` via. my base system repositories so that I can generate all documentation before feeding it into the MinGW compiler and this works fine.
See #2995 for more information.
> Removed qhelpgenerator and qcollectiongenerator references for Qt5::Help

- src/poppler-qt5-1-win32.patch
- src/poppler-qt5.mk
- src/poppler-qt6-1-win32.patch
- src/poppler-qt6.mk
- fix static Qt6 build involving qt6-qtimageformats
- apply the ENABLE_RELOCATABLE patch on the poppler-qt builds
- add qtimageformats/qt6-qtimageformats to the dependencies
Thanks!
> poppler-qt static build fixes

- src/guile.mk
Currently, package `guile` for target `i686-w64-mingw32.static` fails to build.  This is due to `-Werror` being specified and an indentation warning being issued, thus halting compilation.  This is a small change that adds `-Wno-misleading-indentation` to the compiler flags, which allows the package to be built successfully.  This will resolve issue #3055.
> Fix build failure for package `guile` target `i686-w64-mingw32.static`

- src/gtk2.mk
Currently, package `gtk2` target `i686-w64-mingw32.static` fails to build.  This is due to linker errors while trying to run the test compilation in `src/gtk2.mk`.  For some reason or other, the linker is not informed that it needs to link against `libstdc++`, which causes a lot of `undefined reference` errors when trying to link `usr/i686-w64-mingw32.static/lib/libcairo.a`.  Simply adding `-lstdc++` fixes this problem and allows GTK2 to compile sucessfully.
> Fix build failure for pakage `gtk2`

- src/cairo.mk
- src/pixman.mk
Since 1125fa7, cairo and pixman builds use meson-wrapper but it is not in dependencies.
Now clean build always installs meson-wrapper first.
> Add meson-wrapper dependency to cairo and pixman

- src/freeimage-1-fixes.patch
Freeimage's build is currently broken, this unbrokens it.  It throws lots of nasty errors because "ISO C++17 does not allow dynamic exception specifications" according to the compiler.  Enforcing C++14 fixes this.  Another very, very weird thing is that somehow, somewhy, `WIN32` isn't defined **anywhere** in the build process, and this completely breaks a **lot** of conditional compilation stuff, which cropped up in a lot of weird ways.  Simply adding it to the compiler flags fixes everything.  It was that simple, yet it took me 4 days, several false starts, and having to go figure out completely unrelated problems (that patch file has **mixed line endings** in it!) to get to this point.  I hate everything now and have almost lost my sanity, but at least it's fixed.
Also, I can add a …
> Fix `freeimage`'s broken build

- docs/index.html
Package proj fails to build without sqlite3, and package glib fails to build without the python module packaging, so add them to the requirements.
This should probably be revisited later to add the packages for other distros, but it's good enough for right now.
> Add `python3-packaging` and `sqlite3` to Debian requirements list

- src/gtk3.mk
This is yet another fix for yet another instance of cairo now needing to link against libstdc++, which the package's build process isn't expecting, which causes the linker to throw its hands up and bomb out because it's too dumb to automatically bring in the standard libraries when needed.
> Fix gtk3 failing to build because of cairo's stupid libstdc++ dependencies

- plugins/gcc14/gcc14.patch
Fixes boost build for i386.
Patch proposed here: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=114968
> gcc14: fix signature of __cxa_thread_atexit

- src/assimp.mk
New versions of `assimp` does not use Boost. Dependency removed.
Removed CMake options are the ones already by default.
Replaced gcc call by g++ to fix static builds (see https://github.com/assimp/assimp/blob/v5.4.1/code/CMakeLists.txt#L1348).
> assimp: update 3.2 -> 5.4.1

- src/curl.mk
Now that `libnghttp2` was added in #3078, curl can be built with http2 support
> Build curl with http2 support

- src/qt/qt6/qt6-qt5compat.mk
- src/qt/qt6/qt6-qtvirtualkeyboard.mk
- src/qt/qt6/qt6-qtwebview.mk
I simply copied `qt-websockets.mk` and adjusted the names + checksums.
In addition, I included the `qtshadertools` as dependency in `qt5compat` module. This causes the `GraphicalEffects` module to being built, which is not the case if shadertools is not yet available during the build. I think this is the better default to have
> Qt6.8.0: Add virtualkeyboard and webview modules, extend deps of qt5compat

- src/flint-1-fixes.patch
- src/flint-test.c
- src/flint.mk
This PR adds C library FLINT (https://flintlib.org/).  Currently, FLINT does not support out-of-tree builds, so we build in `$(SOURCE_DIR)`.  There are plans for this to be fixed in an upcoming release:
https://github.com/flintlib/flint/issues/2077
The patch addresses non-portable use in their `Makefile.in` of linker option `-r` to merge object files.  The MinGW back-end of LLVM's linker `lld` does not support it.  The patch has been provided upstream:
https://github.com/flintlib/flint/issues/2098
I've already succeeded in using my fork to cross-compile FLINT for `x86_64` and `aarch64`, and I've tested each of the resulting builds locally inside of Msys2.  No problems so far.
Please let me know if I've missed anything!
> Add package flint, version 3.1.3-p1 to MXE

- tools/copydlldeps.sh
The --infile argument in copydlldeps.sh was not usable anymore since be2e33c9d4bfec190eea3b996579e551c1bf906f (copy-paste error in variable name "$curPath" vs "$curFile").
> copydlldeps.sh: Fix --infile processing

- src/hyperscan-1-fixes.patch
- src/hyperscan.mk
Fix error: "error: narrowing conversion of '161' from 'int' to 'char' [-Wnarrowing]" in generated files src/parser/control_verbs.cpp and util/ExpressionParser.cpp.
hyperscan: update from 5.4.0 to 5.4.2.
hyperscan: update website
> hyperscan: fix build on arm64 host

- docs/index.html
Add a similar note that g++-multilib and libc6-dev-i386 are not required.
> installation requirements for Debian arm64

- src/libgit2.mk
This patch enables SSH (libssh2) support with libgit2. SSH support is disabled by default, even when libssh2 is available. I assume it was the intention to use libssh2 as it was already declared as MXE dependency in libgit2.mk.
This patch also explicitly sets pcre as a dependency. Without this setting, the result would depend on whether MXE package pcre has already been built or not: either the MXE pcre would get used, or a bundled pcre. This patch makes libgit2 predictably use "system" PCRE from MXE. In principle, one could instead use pcre2, as Msys2 does via `-DREGEX_BACKEND=pcre2`.
This patch also explicitly sets zlib as a dependency. Zlib is used (and is correctly declared as pkg-config dependency).
> Enable SSH support. Always use system PCRE. Declare dependency on zlib.

- src/glib.mk
This fixes the build of the native part of glib2, when targeting static libraries, on systems where gobject introspection is detected to be present, such as Ubuntu 24.04. Without the fix, the build fails compiling `girparser.c` on the grounds of null pointer dereference (-Wnull-dereference); this warning can be disabled, but the build then still fails for another reason.
From my reading, gobject instrumentation cannot be built as a static library and static libraries cannot have introspection data. When building the target/windows version of glib, gobject instrumentation is automatically disabled because it is not present. Some other MXE packages disable introspection explicitly and unconditionally for the target build.
> Disable introspection to fix native build.

- src/nlohmann-json-test.cpp
- src/nlohmann-json.mk
Add new package for [nlohmann-json](https://github.com/nlohmann/json).
Also tested with GCC 6-10 & 12-14 from the `plugins/` directory.
GCC 5 is not working.
> nlohmann-json: Add new package

- src/agg.mk
- src/aubio.mk
- src/icu4c.mk
- src/upx.mk
- src/waf-1-fixes.patch
This PR adds some simple fixes for issues I encountered while building packages for a Debian 12 (bookworm) aarch64 build environment (with a target of i686-w64-mingw32.static-gcc (GCC) 11.5.0).
* icu4c: This package (I believe unintentionally) removed `libicu.a` from mingw32, which led to issues building the mingw32 package when `libicu.a` had disappeared.
* agg: add `-fpermissive` due to some pointer arithmetic that now throws a compiler warning without `-fpermissive`.
* upx: Disable "misleading indentation" warning from a macro, and build with `-funsigned-char` (as required by this package, expressed in a `static_assert`).
* aubio/waf: Backport some waf build system patches for compatibility with Python 3.11. Another option would be to upgrade Waf to the 2.x release and patch aubio to …
> GCC 11.5/Debian 12 Package Build Fixes

- src/libxml2.mk
This fixes the update script to look at newer versions. Without the fix, one gets something like:
```
OLD      libxml2  2.13.5 --> 2.12.10 ignoring
```
> Fix update script (update to newer versions).

- src/eigen.mk
This fixes the update script of the package: `$` has to be escaped in make file, otherwise the update results in:
```
sed: -e expression #1, char 51: unterminated `s' command
Unable to update version number of package eigen
```
> Escape dollar character in update script.

- src/itk-1-fixes.patch
Resolves issue #3056.
VNL's `vnl_bignum.cxx` referenced `std::numeric_limits` without including the `<limits>` header (https://en.cppreference.com/w/cpp/types/numeric_limits). Presumably more permissive compilers used to bring in this header directly, or other STL headers used to include it.
After applying this patch, itk builds cleanly for i686.
Original error:
```
../../../../../../../../ITK-5.0.1/Modules/ThirdParty/VNL/src/vxl/core/vnl/vnl_bignum.cxx: In member function 'vnl_bignum::operator float() const':
../../../../../../../../ITK-5.0.1/Modules/ThirdParty/VNL/src/vxl/core/vnl/vnl_bignum.cxx:716:37: error: 'numeric_limits' is not a member of 'std'
../../../../../../../../ITK-5.0.1/Modules/ThirdParty/VNL/src/vxl/core/vnl/vnl_bignum.cxx:716:52: error: expected primary-expression …
```
> Add missing std::numeric_limits include for itk.

- src/gcc-1-fixes.patch
- src/gcc.mk
Fixes 2 uncommon build issues with GCC:
1. If the `mman-win32` package has been installed when `gcc` is (re-)built, gcov (as part of libgcc) will depend on `mmap()`, due to the presence of `sys/mman.h` (installed by mman-win32). This results in a link error building the test executable with `--coverage`.
2. If `getpagesize()` is not defined when libbacktrace is built, libbacktrace will provide its own definition (which is typical for mingw builds, see https://gcc.gnu.org/bugzilla/show_bug.cgi?id=95012).
However, the config macro was not used properly when added to gcc ([change implemented here](https://gcc.gnu.org/git/gitweb.cgi?p=gcc.git;h=47f4703c33c4936fd423c2a1180b2de144115d3d)). `AC_CHECK_DECLS` will define `HAVE_DECL_` to `0` or `1`, instead of `#define` or `#undef`. This patch …
> gcc: Avoid mmap() dependency in gcov, define getpagesize() for libbacktrace

- src/botan2.mk
This is my first time making a package for MXE, so please let me know if I am not following best practices. I have read http://mxe.cc/#creating-packages and borrowed heavily from existing packages.
I verified the .a and .pc files are installed, and was able to create a $(PKG)_UPDATE section.
Once this package is acceptable to merge in, I would like to make a .deb package for it so I can host it on my apt repo. Are there instructions on how to do so?
Here's how I tested my .mk file (on a fresh installation of Debian 12):
```sh
git clone https://github.com/hax0rbana-adam/mxe
cd mxe
git checkout libbotan2
sudo apt-get install -y autoconf automake autopoint bash bison bzip2 flex g++ g++-multilib gettext git gperf intltool libc6-dev-i386 libgdk-pixbuf2.0-dev libltdl-dev libgl-dev libpcre3-dev …
```
> adding new libbotan2 package

- src/argon2.mk
Added the argon2 library. It creates and installs .a and .pc files, the file is named argon2.mk instead of libargon2.mk, and it uses $(PKG)_GH_CONF to download releases from GitHub. :slightly_smiling_face: 
Building this was tested on Debian 12 as follows:
```sh
git clone https://github.com/hax0rbana-adam/mxe
cd mxe
git checkout libargon2
sudo apt-get install -y autoconf automake autopoint bash bison bzip2 flex g++ g++-multilib gettext git gperf intltool libc6-dev-i386 libgdk-pixbuf2.0-dev libltdl-dev libgl-dev libpcre3-dev libssl-dev libtool-bin libxml-parser-perl lzip make openssl p7zip-full patch perl python3 python3-distutils python3-mako python3-packaging python3-pkg-resources python3-setuptools python-is-python3 ruby sed sqlite3 unzip wget xz-utils
time make …
```
> argon2: adding new package

- src/qttools-1-fixes.patch
This PR removes the patch which disables building windeployqt.
I need windeployqt for building KeePassXC with MXE, but it was patched out of qttools when [fixing a problem with building documentation](https://github.com/mxe/mxe/issues/2324) back in 2019. I don't know if [that patch](https://github.com/mxe/mxe/pull/2325/files) was needed at the time, but I can confirm that it is not needed now.
Tested on Debian 12.
```sh
sudo apt-get install -y autoconf automake autopoint bash bison bzip2 flex g++ g++-multilib gettext git gperf intltool libc6-dev-i386 libgdk-pixbuf2.0-dev libltdl-dev libgl-dev libpcre3-dev libssl-dev libtool-bin libxml-parser-perl lzip make openssl p7zip-full patch perl python3 python3-distutils python3-mako python3-packaging python3-pkg-resources python3-setuptools …
```
> re-enable building windeployqt

- src/qt/qt6/qt6-qtcharts.mk
The qtcharts module does not correctly build without a dependency to qtdeclarative
> Add missing dependency to qt6-qtcharts.mk

- src/libmpeg2-9999-fix-win64.patch
https://github.com/scummvm/dockerized-bb/blob/master/toolchains/mxe/packages/libmpeg2/libmpeg2-9999-fix-win64.patch
https://forums.scummvm.org/viewtopic.php?f=2&t=16293
```
Thread 1 received signal SIGSEGV, Segmentation fault.
0x00007ff66119b240 in mpeg2_idct_copy_sse2 ()
(gdb) backtrace
#0  0x00007ff66119b240 in mpeg2_idct_copy_sse2 ()
#1  0x00007ff661195952 in mpeg2_slice ()
#2  0x00007ff66118aaa4 in mpeg2_parse ()
```
> libmpeg2: fix for win64
