- src/pfstools-test.cpp
- src/pfstools.mk
The update requires a move from autoconf to cmake.
> pfstools: update to 2.0.0, add test program.

- index.html
- src/liblaxjson-test.c
- src/liblaxjson.mk
part of an effort to get [Legend of Swarkland](https://github.com/thejoshwolfe/legend-of-swarkland) to build with mxe.
> add liblaxjson package

- src/freeimage.mk
> freeimage pkg-config should depend on libstdc++

- src/ffmpeg.mk
- src/libass.mk
- src/luajit.mk
> update ffmpeg and libass, add missing luajit dependency

- index.html
- src/jansson.mk
Hello, 
I have created a simple mxe package for Jansson JSON library; http://www.digip.org/jansson/ 
There is no PKG_UPDATE or test program for it. I'm not actually writing the code against the library myself, just building other code. So I'm not having good idea of the test program.
> Jansson package

- index.html
- src/armadillo.mk
- src/hdf4.mk
- src/netcdf.mk
- src/openjpeg-1-dllfix.patch
- src/openjpeg-2-dllmacro.patch
- src/openjpeg.mk
- src/portablexdr-1-castfix.patch
- src/portablexdr.mk
> enable shared libs for gdal dependencies 

- src/portaudio-2-wdmks.patch
- src/portaudio.mk
> Enable WDM/KS support for PortAudio

- index.html
- src/rucksack-1-freeimage.patch
- src/rucksack-test.c
- src/rucksack.mk
Previous pull request: #629 
This package adds [rucksack](https://github.com/andrewrk/rucksack), a texture packer and resource bundler.
> add rucksack package

- src/sfml-1-fixes-crlf.patch
- src/sfml.mk
CMakeLists.txt changed, so I regenerated the patch.
> sfml: update to 2.2

- index.html
- src/libsvm-1-cmakelists.patch
- src/libsvm.mk
> libsvm: add package

- index.html
- src/libcomm14cux.mk
- src/qtwebkit.mk
- versions.json
> New package: libcomm14cux

- src/openexr.mk
Updates:
- gcc to 5.2
- OpenEXR to 2.2.0
(I tried to fix OpenCV, but gave up :()
> Software updates

- tools/build-pkg.lua
* fix a pattern in blacklist
* take target common files to a package
* build for amd64 only
* fix build success detection
https://lists.nongnu.org/archive/html/mingw-cross-env-list/2015-06/msg00011.html
> improvements of build-pkg

- index.html
- src/tclap.mk
Based on http://lists.nongnu.org/archive/html/mingw-cross-env-list/2015-08/msg00015.html
> add package tclap

- src/wt-1-fixes.patch
- src/wt-2-rename-variables-near-and-far.patch
- src/wt.mk
* update WtFindSsl.txt patch
* remove WRasterImage.C patch: the file was removed
* remove fixes for boost: ported to upstream
* add patch for WCartesian3DChart (rename conflicting names)
> update package wt from 3.3.1 to 3.3.4

- index.html
- src/berkeleydb.mk
- src/db.mk
tested. im not sure with build process, but i can use it.
> new package berkeleydb

- index.html
- src/libtorrent-rasterbar-1-getfileattributesex.patch
- src/libtorrent-rasterbar-2-geoip-win32.patch
- src/libtorrent-rasterbar-3-geoip-include-winsock2-before-windows.patch
- src/libtorrent-rasterbar-4-ed25519-seed-fix-includes.patch
- src/libtorrent-rasterbar.mk
**libtorrent** (aka libtorrent-rasterbar) is a feature complete C++ bittorrent implementation focusing on efficiency and scalability. It runs on embedded devices as well as desktops. It boasts a well documented library interface that is easy to use. It comes with a simple bittorrent client demonstrating the use of the library.
The main goals of libtorrent are:
*  to be cpu efficient
*  to be memory efficient
*  to be very easy to use
http://www.libtorrent.org/
See #812
> add package libtorrent-rasterbar

- src/plib-1-fixes.patch
- src/plib-2-build-shared-libs.patch
- src/plib.mk
Add the ability to build plib for the 64-bit configuration and a shared build configuration.
> Add plib shared and 64-bit builds

- Makefile
- src/assimp.mk
- src/boost.mk
- src/hdf5.mk
- src/mxe-conf.mk
- src/pkgconf.mk
- src/qt.mk
- src/qtbase.mk
> Refactor MXE configuration and cmake toolchain

- tools/build-pkg.lua
See https://github.com/mxe/mxe/pull/836#issuecomment-139034608
> build-pkg: add env. var. MXE_DIR and MXE_NO_DEBS

- src/gdal.mk
Works on Debian Jessie as well.
close #862
> fix gdal build on Debian Wheezy

- tools/build-pkg.lua
> build-pkg: report DLL files in /lib/

- tools/build-pkg.lua
* dereference symlinks
* use `--brief`
> build-pkg: improve launching file tool

- Makefile
Found following problems:
* MXE Warning! Downloading muparser from backup.
* MXE Warning! Downloading openscenegraph from backup.
* MXE Warning! Downloading suitesparse from second URL.
> report downloading from backup

- index.html
In this game the player should help a girl by name of Violet to struggle with hordes of monsters. For this purpose the various weapon, and also the special abilities of the heroine which are opening with experience can be used.
> Add violetland to used by section

- index.html
Sorted list of projects using mxe alphabetically since it was neither alphabetical nor chronological. Makes it hard to add new projects.
> Changed used by section to alphabetical order

- index.html
- src/cimg-1-add-option-exe-suffix-exesfx.patch
- src/cimg-2-split-cflags-to-define-and-incdir.patch
- src/cimg.mk
The [CImg Library](http://cimg.eu/) is a small, open-source, and modern C++ toolkit for image processing, designed with these properties in mind.
This pull request depends on following pull requests:
* #875 imagemagick: enable shared build
* #876 fftw: compile with combined thread libraries
> add package cimg

- src/qt-test.cpp
- src/qt-test.hpp
- src/qt-test.pro
- src/qt-test.qrc
Qt header is translated to C++ code by `moc` tool.
Qt resource file (.qrc) is translated to C++ code by `rcc` tool.
> Qt: test more Qt tools (moc, rcc)

- src/qt.mk
- src/qtbase.mk
Add MOC and RCC commands and files produced to the test.
close #883
> qt and qtbase: fix the test built the manual way

- Makefile
Source: https://github.com/mxe/mxe/pull/649#issuecomment-143390677
> add macro MXE_GET_GITHUB_TAGS

- index.html
- src/unrtf-1.patch
- src/unrtf.mk
This is a tool for converting RTF (rich text format) to several usable formats. As far as I know, there is no portable library that does this, so unrtf is useful for applications that need this functionality.
> new package: unrtf

- tools/build-pkg.lua
I faced with the problem after running build-pkg on this machine many-many times. Finally I found this method how to fix it without restarting the machine.
> build-pkg: add a note about fakeroot ipc problem

- src/widl.mk
with CMAKE_WIDL indicating the path of the widl executable
> widl: generation of widl.cmake 

- src/openscenegraph-1-fix-case-in-headers.patch
- src/openscenegraph-2-fix-case-in-library-ws2-32.patch
- src/openscenegraph-3-fix-pointer-to-int-conversion-on-64bit.patch
* fix case in headers windows.h and winsock2.h
* fix case in library wc2_32
* fix pointer to integer conversion on 64 bits
close #913
> fix openscenegraph build

- src/openscenegraph-3-fix-pointer-to-int-conversion-on-64bit.patch
> Fix OpenSceneGraph patch.

- src/cmake/modules/FindFriBiDi.cmake
Now the following CMake code finds FriBiDi:
```cmake
find_package(FriBiDi)
```
> add CMake module FindFriBiDi.cmake

- tools/build-pkg.lua
> build-pkg: install source, refactoring and other improvements

- index.html
- src/ucl-1-fixes.patch
- src/ucl.mk
See also #813
**UCL** is a portable lossless data compression library written in ANSI C.
http://www.oberhumer.com/opensource/ucl/
> add package ucl

- tools/build-pkg.lua
Example:
```
[  4/100] The build is expected to complete in 0.3 hours, on Thu Oct 29 23:03:27 2015
```
> build-pkg: print progress

- src/aubio.mk
> aubio: disable txt2man and doxygen docs

- tools/build-pkg.lua
> build-pkg: add EOL after last line in *.list file

- Makefile
- index.html
- tools/build-pkg.lua
- tools/nonetwork.c
> disable networking with LD_PRELOAD when build

- tools/travis-push.sh
See #924
See https://travis-ci.org/mxe/mxe/builds/91781012#L99
> suppress git commit error in Travis

- index.html
- src/cryptopp-1-fixes.patch
- src/cryptopp-test.cpp
- src/cryptopp.mk
This patch adds cryptopp, the open source cryptography licensed under Boost Software License 1.0
> add cryptopp (https://www.cryptopp.com/)

- src/ossim.mk
merge this only after merging  https://github.com/mxe/mxe/pull/1027
> OSSIM: 1.8.18 -> 1.8.20-1

- plugins/apps/tor.mk
Tor is free software and an open network that helps you defend
against traffic analysis, a form of network surveillance that
threatens personal freedom and privacy, confidential business
activities and relationships, and state security.
https://www.torproject.org/
Previous attempt: #808
> add package "tor" to plugin "apps"

- src/gcc.mk
See https://github.com/mxe/mxe/pull/1017#issuecomment-161243848
* any future side-by-side installs will use targets as a higher level
directory separation, we don't want to mix libs built with different
versions of the compiler.
* add note about keeping `--enable-version-specific-runtime-libs`
* remove TODO, there's no sane way to configure the install
```
$ find usr -name libgcc_s_*.dll
usr/i686-w64-mingw32.shared/bin/libgcc_s_sjlj-1.dll
usr/i686-w64-mingw32.shared.posix/bin/libgcc_s_sjlj-1.dll
usr/x86_64-w64-mingw32.shared/bin/libgcc_s_seh-1.dll
usr/x86_64-w64-mingw32.shared.posix/bin/libgcc_s_seh-1.dll
```
> gcc: don't install *.dlls to version specific directory

- src/gcc-1.patch
- tools/patch-tool-mxe
> Patch tool improvements

- src/lua.mk
> lua: use libluaX.Y.dll naming convention

- Makefile
fixes #952 and should provide a general solution.
> disable doxygen in MXE_CONFIGURE_OPTS

- tools/build-pkg.lua
> build-pkg: pack Debian packages with xz not gzip

- tools/build-pkg.lua
> build-pkg: update list of files back from .tar.xz

- README.md
- index.html
> doc updates: fix typo, update package counts, note posix threads support

- src/freeimage-test.cpp
- src/freeimage.mk
Install the C++ wrapper of freeimage as well
> also build and install FreeImagePlus

- src/libmysqlclient-1-fixes.patch
> Fix libmysqlclient if MXE's path contain special characters

- src/opencv-5-fix-in-bad-dir.patch
> opencv: fix CMake error if a directory contains ++

- src/freeimage-2-fixes.patch
- src/freeimage.mk
Alas, I broke the freeimage build.  I was gone for the weekend and therefore only noticed now.  Sorry for this.
> fix freeimage build

- src/boost-1-fixes.patch
See https://github.com/mxe/mxe/issues/1104#issuecomment-167437968
> boost: remove unneeded patch "Fixed case sensetive for linux mingw"

- src/lapack.mk
> lapack: fix case change in 3.6.0 update

- src/alure.mk
> add mpg123 to alure's dependencies

- tools/build-pkg.lua
Log of full build of commit 815d8fe7e18deb2ae50ade063f98cfdd6d155581 + 3 commits of this pull request: https://gist.github.com/45615365c6fb51beca77
> build-pkg: add toposort checks and implement it internally, without tsort tool

- Makefile
https://github.com/mxe/mxe/issues/1108#issuecomment-168490205
> print Python version to log

- index.html
> add links to pkg.mxe.cc and battleship to index.html

- src/lua-1-fixes.patch
- src/lua.mk
luarocks built and tested: success.
fix #1060
> lua: disable readline on linux, macosx and freebsd

- src/ossim.mk
> ossim: add missing libgeotiff dependency

- tools/s3-fetch-and-sync
* use bash for brace expansion
* http://sprunge.us/ is down (fixes #1145)
> fix backup download

- patch.mk
- src/libieee1284-1-fixes.patch
see https://github.com/mxe/mxe/issues/1170
> fix libieee1284 on Wheezy and prevent patch-tool-mxe from using rename

- Makefile
- src/mxe-conf.mk
https://github.com/mxe/mxe/pull/1061/files#r49049496
https://github.com/mxe/mxe/issues/1111#issuecomment-169280181
> mxe-conf: create basic non-empty directory hierarchy

- src/gnutls.mk
> gnutls: add missing libidn dependency

- plugins/native/patch.mk
> add gnu patch to native plugins

- tools/build-pkg.lua
> build-pkg: detect undeclared dependencies

- src/qtbase-1-fixes.patch
- src/qttools-test/CMakeLists.txt
- src/qttools-test/mxe-cmake-qtuitools.cpp
- src/qttools.mk
See https://github.com/mxe/mxe/issues/1185
> Qt5 cmake rearrange targets

- src/openscenegraph-1-fixes.patch
- src/openscenegraph.mk
> openscenegraph: disable ffmpeg

- tools/copydlldeps.sh
Fix #1226
multiCall was added in https://github.com/mxe/mxe/pull/1227
> copydlldeps.sh: fix #1226 (case insensitive)

- index.html
- src/qtsparkle_qt4-test.cpp
- src/qtsparkle_qt4.mk
This is the last required dependency for build of Clementine.
> add package qtsparkle

- tools/nonetwork.c
See https://github.com/mxe/mxe/issues/1269
> nonetwork: print message from replaced functions

- src/cmake.mk
separate pull request for cmake update as requested in #1279
> cmake: update to 3.5.1

- plugins/apps/luajit.mk
- plugins/apps/wrk-1-fixes.patch
- plugins/apps/wrk.mk
- src/luajit.mk
wrk is modern HTTP benchmarking tool.
> add package "wrk" to plugins/apps

- Makefile
It provides interactive shell with the environment of MXE build.
> add "make shell" command

- tools/build-pkg.lua
> build-pkg: limit number of retries of downloading

- plugins/native/trusty/gettext.mk
- plugins/native/trusty/libiconv.mk
> add native build of gettext for Ubuntu 14.04 Trusty

- src/libxslt.mk
> libxslt: enable shared

- Makefile
> add host compiler version to log

- Makefile
- index.html
- src/hdf-eos2-1-fixes.patch
- src/hdf-eos2-test.c
- src/hdf-eos2.mk
- src/hdf-eos5-1-fixes.patch
- src/hdf-eos5-test.c
- src/hdf-eos5.mk
(no matter what the names suggest, HDF-EOS2 and HDF-EOS5 are 2 completely different libraries, one building on HDF4 and the other on HDF5)
> Add HDF-EOS libraries

- tools/install-deps
Otherwise it will make interactive prompts.
> install-deps: several improvements on Debian Jessie

- src/openblas.mk
missing since #958
fixes #1384
> openblas: add pthreads dependency

- src/qtserialport_qt4.mk
- src/qtsystems.mk
> Fix checksum of qtserialport_qt4

- plugins/README.md
> plugins/README: clarify how to enable many plugins

- Makefile
> fix multiple downloads of same file

- plugins/go/README.md
- plugins/go/go-1-fixes.patch
- plugins/go/go-native.mk
- plugins/go/go.mk
- plugins/go/src/mxe-test/main.go
Plugin description lives in [README.md](https://github.com/LuaAndC/mxe/blob/go/plugins/go/README.md).
> add Go plugin

- index.html
- src/yaml-cpp-1-fixes.patch
- src/yaml-cpp-test.cpp
- src/yaml-cpp.mk
> add yaml-cpp (second attempt)

- tools/build-pkg.lua
See https://github.com/mxe/mxe/pull/1443#issuecomment-233181951
> build-pkg: do not omit gitignored files in usr

- src/aubio.mk
Please read the issue #1374 for more details
> Solved #1374 problem compiling aubio

- src/poppler-1-win32.patch
fix https://github.com/mxe/mxe/issues/1455
> poppler: do not try to use mman.h

- tools/build-pkg.lua
fix https://github.com/mxe/mxe/issues/1471
> build-pkg: fix crash if package breaks in 1st pass

- src/cloog.mk
- src/gcc.mk
- src/isl.mk
Tested on all four targets, list of changes:
https://gcc.gnu.org/bugzilla/buglist.cgi?bug_status=RESOLVED&resolution=FIXED&target_milestone=4.9.4
> update gcc 4.9.3 --> 4.9.4

- plugins/examples/host-toolchain/binutils-host.mk
- plugins/examples/host-toolchain/gcc-host.mk
See https://github.com/mxe/mxe/issues/950#issuecomment-238112271
> host-tools plugin: install prefixed binutils and strip binaries

- src/libical.mk
See:
https://github.com/libical/libical/issues/238
https://github.com/libical/libical/issues/233
> libical: disable parallel build

- src/cegui-1-fixes.patch
- src/cegui.mk
Boost and SDL2 aren't detected and need more work, other packages are
either outdated or missing from MXE.
> cegui: fix libxml2 and minizip; enable fribidi and glfw3

- src/tinyxml.mk
- src/tinyxml2.mk
> tinyxml updates

- src/qt.mk
> qt: allow user overrides of build options

- src/xvidcore.mk
See https://github.com/mxe/mxe/pull/1454#issuecomment-235508913
**Work-in-progress!** It builds here, but I have not compared lists of files.
> xvidcore: _SUBDIR is top-level directory

- src/dlfcn-win32.mk
- src/gdb.mk
> gdb: fix dlfcn detection

- LICENSE.md
Following on from #1503, the actual text probably needs updating.
Largely inspired by https://github.com/JuliaLang/julia/blob/master/LICENSE.md
Closes #520
> update LICENSE.md for third-party sources

- tools/build-pkg.lua
> build-pkg: system requirements are recommendations not dependencies

- docs/index.html
- src/libnice.mk
An glib based [ICE](https://en.wikipedia.org/wiki/Interactive_Connectivity_Establishment) library.
> new package: libnice

- src/gsl.mk
I followed this guide: https://github.com/mxe/mxe/wiki/Adding-Shared-Support-to-Packages
Also I followed the pre-commit checklist and made sure the files are there and in the right places.
> Enable shared builds for gsl

- plugins/go/go-native-1-fixes.patch
See https://github.com/golang/go/issues/13896
> fix build of go-native on Debian 8 Stretch

- plugins/apps/msmtp.mk
Add msmtp 1.6.5; as suggested by starius this is in plugins/apps:
https://github.com/mxe/mxe/issues/1567
> Add msmtp to plugins/apps

- src/qtbase-1-fixes.patch
Fix https://github.com/mxe/mxe/issues/1572
> qtbase: Fix wrong assert

- docs/index.html
- src/googlemock.mk
- src/googletest.mk
- src/protobuf.mk
Requested in https://github.com/mxe/mxe/pull/1277#issuecomment-257080933
> protobuf: update to 3.1.0 and compile host protoc as native package

- Makefile
Slow HTTP server with lag for tests:
https://gist.github.com/45472174f8bd97989c1eb9bc64d50468
Fix https://github.com/mxe/mxe/issues/1552
> pkg download: do not append to previous attempt

- src/vmime.mk
See https://github.com/kisli/vmime/issues/151#issuecomment-265280156
Fix https://github.com/mxe/mxe/issues/1586
> update vmime to b1b3f30

- tools/install-deps
See https://github.com/mxe/mxe/issues/1593
> install-deps: install libtool-bin on Debian Sid

- src/freetds.mk
fix https://github.com/mxe/mxe/issues/1596
> freetds: add HTTP download URL

- docs/index.html
- src/libcddb-1-fixes.patch
- src/libcddb-test.c
- src/libcddb.mk
- src/libdvdetect.mk
- src/neon-test.c
- src/neon.mk
Replacement for https://github.com/mxe/mxe/pull/1591
> add libcddb, libdvdetect and neon

- src/gtkmm2.mk
- src/gtkmm3.mk
Auto_ptr make GCC 5.4.0 angry.
See https://github.com/mxe/mxe/pull/1541#issuecomment-269065070
> gtkmm2, gtkmm3: fix build for GCC 5.4.0

- Makefile
see https://github.com/mxe/mxe/issues/1614
> make core to be the first item of MXE_PLUGIN_DIRS

- src/hamlib-test.c
- src/hamlib.mk
adding hamlib to mxe, adjusted to the new style pushed by @starius, writing homepage and description into the *.mk file. hamlib-test.c included.
> Introducing hamlib

- src/gst-plugins-bad-1-fixes.patch
- src/gst-plugins-bad.mk
fix https://github.com/mxe/mxe/issues/1619
> gst-plugins-bad: depend on neon and fix its header

- src/gst-plugins-bad.mk
- src/gst-plugins-base.mk
- src/gst-plugins-good.mk
- src/gst-plugins-ugly.mk
- src/gstreamer.mk
see #1288, https://github.com/mxe/mxe/pull/1277#issuecomment-255899589
> fix moving gstreamer dlls (#1288)

- Makefile
See http://lists.nongnu.org/archive/html/mingw-cross-env-list/2017-01/msg00005.html
fix https://github.com/mxe/mxe/issues/1629
> add new packages backup: gitlab

- src/fftw.mk
tarball has been removed, see: https://github.com/FFTW/fftw3/commit/6fb9cd7b6359f29ce488a5802793139971d59c6c
> fftw: update with packaging bugfix

- Makefile
> Makefile: fix target validation checks

- plugins/apps/clementine_qt4.mk
- src/liblastfm_qt4-test.cpp
- src/liblastfm_qt4.mk
https://github.com/mxe/mxe/issues/1356
Clementine from Debian has used this library.
> add package liblastfm_qt4

- src/gtk3-1-fixes.patch
Yak shaving for https://github.com/mxe/mxe/issues/1647
> gtk3: unify patch

- src/libepoxy-1-fixes.patch
- src/libepoxy-test.c
- src/libepoxy.mk
See https://github.com/mxe/mxe/issues/1647#issuecomment-275967915
> libepoxy: fix linking in static targets and add test

- docs/index.html
See http://lists.nongnu.org/archive/html/mingw-cross-env-list/2016-01/msg00022.html
> index.html: add "How to choose MXE target"

- Makefile
- src/levmar.mk
> allow to change User Agent; fix levmar download

- src/qtwebkit.mk
fix https://github.com/mxe/mxe/issues/1662
> qtwebkit: fix downloading on Jessie

- plugins/apps/clementine_qt4.mk
- src/gst-plugins-bad.mk
- src/libmms-1-fixes.patch
- src/libmms-test.c
- src/libmms.mk
libmms is required by clementine for playing some radio stations.
> add package libmms

- src/armadillo.mk
fix https://github.com/mxe/mxe/issues/1699
> armadillo: fix download URL

- src/libsvm.mk
3.20 is no longer available on the website.
> libsvm 3.22

- tools/mxe-get
*BSD systems are currently supported and macOS actually tested.
Ref: https://github.com/mxe/mxe/issues/1708
> add bash script to install packages on non-Linux systems

- src/libf2c.mk
Fix https://github.com/mxe/mxe/issues/1719
> libf2c: update checksum

- docs/index.html
* remove internal use only from updates and cleanup-style
* note usage of `make check-update-package-foo`
> Docs update

- src/gtk3-1-fixes.patch
- src/gtk3.mk
Static and shared build works with this patch
> Fix broken shared build of GTK3

- src/gnutls-1-fixes.patch
fix https://github.com/mxe/mxe/issues/1753
See https://github.com/mxe/mxe/issues/1753#issuecomment-298772548
> Fix gnutls.pc

- Makefile
Needed for https://github.com/mxe/mxe/pull/1752
> add dist_bin_SCRIPTS to MXE_DISABLE_PROGRAMS

- src/hunspell-test.cpp
- src/hunspell.mk
Development has moved from Sourceforge to GitHub.
> Update hunspell to 1.6.1

- src/libsoup.mk
fix https://github.com/mxe/mxe/issues/1768
> libsoup: do not use Apache

- Makefile
> build-matrix: fix detection of native virtual packages

- src/pkgconf-1-fixes.patch
- src/pkgconf.mk
- src/qtbase.mk
- src/sqlite.mk
Better approach to cleaning up cflags proposed by Tony.
> Clean cflags v3

- src/freetype-1-fixes.patch
> freetype: use prefixed pkg-config in freetype-config script

- docs/index.html
> osx: note workaround for recent Xcode versions

- docs/index.html
See http://lists.nongnu.org/archive/html/mingw-cross-env-list/2017-06/msg00001.html
> homepage: s/MXE_TARGET/MXE_TARGETS/

- docs/index.html
See:
https://github.com/mxe/mxe/issues/593#issuecomment-300228919
> debian requirements: move libtool-bin to main section

- src/flac.mk
- src/libshout.mk
- src/llvm.mk
- src/ogg.mk
- src/speex.mk
- src/speexdsp.mk
- src/theora.mk
- src/vorbis.mk
> secure URLs

- src/djvulibre-1-fixes.patch
- src/djvulibre.mk
> djvulibre: enable static library builds

- src/qtspeech.mk
See http://lists.nongnu.org/archive/html/mingw-cross-env-list/2017-02/msg00013.html
> add qtspeech module

- src/binutils.mk
- src/gcc.mk
> binutils gcc: use MXE_DISABLE_DOC_OPTS

- plugins/native/libtool.mk
- src/libtool.mk
- src/pkgconf.mk
- src/protobuf.mk
Partially built autotools suite can cause race condition
when plugins/native is included
fixes #1851
> add libtool dep for native packages using autotools

- src/cfitsio.mk
> cfitsio: install pkg-config file

- src/cgal-1-fixes.patch
- src/cgal-TryRunResults.cmake
- src/cgal.mk
> Updated cgal to 4.10.

- docs/index.html
Just adding Subsurface to index.html
Signed-off-by: Dirk Hohndel <dirk@hohndel.org>
> Add Subsurface as project using MXE

- src/qtwebkit-1-fixes.patch
- src/qtwebkit-test.cpp
- src/qtwebkit.mk
> qtwebkit: fix crash on startup

- src/x264.mk
> x264: use $(SORT)

- src/cmake-1-fixes.patch
- src/cmake-conf.mk
- src/cmake/conf/mxe-conf.cmake.in
> cmake: add prefixed cpack and CPACK_NSIS_EXECUTABLE

- src/intel-tbb.mk
> add Intel Threading Building Blocks package

- tools/build-pkg.lua
See https://github.com/mxe/mxe/issues/1886#issuecomment-325927308
> build-pkg: ignore all copies of nonetwork.so

- docs/index.html
- plugins/README.md
- plugins/apps/qbittorrent-1-fixes.patch
- src/cmake/modules/FindFriBiDi.cmake
- src/cmake/modules/FindSDL.cmake
- src/cmake/modules/FindSDL_image.cmake
- src/cmake/modules/FindSDL_mixer.cmake
- src/cmake/modules/FindSDL_net.cmake
- src/cmake/modules/FindSDL_sound.cmake
- src/cmake/modules/FindSDL_ttf.cmake
- src/cmake/modules/FindTIFF.cmake
- src/devil-1-fixes.patch
- src/ghostscript-1-fixes.patch
- src/hamlib-test.c
- src/hamlib.mk
- src/minizip-1-unzOpenBuffer.patch
- src/ocaml-core.mk
- src/ocaml-xml-light.mk
- src/opencv-3-fixes-pkgconfig.patch
- src/postgresql.mk
- tools/build-pkg.lua
The tool: https://github.com/client9/gospell
> fix typos found by misspell tool

- Makefile
Ref: https://github.com/mxe/mxe/pull/1899#issuecomment-331723251
> bump primary package mirror to HTTPS

- tools/build-pkg.lua
See https://github.com/mxe/mxe/issues/1886#issue-253920956
See https://github.com/mxe/mxe/issues/968
> build-pkg: pack empty packages as well

- tools/build-pkg.lua
See https://github.com/mxe/mxe/issues/1886#issuecomment-325927828
> build-pkg, Debian: set Installed-Size field

- src/libharu.mk
> libharu: add *.pc file and use for test

- plugins/examples/qt5-freeze/README.md
- plugins/examples/qt5-freeze/qttools-test/CMakeLists.txt
- plugins/examples/qt5-freeze/qttools-test/mxe-cmake-qtuitools.cpp
- plugins/examples/qt5-freeze/qttools.mk
- src/qttools.mk
see: https://github.com/mxe/mxe/issues/1901#issuecomment-333551106
@uwehermann, this should be the last issue with the freeze example - can you confirm?
> qttools: read test from current directory and freeze example 5.7 plugin

- src/pcl.mk
> pcl: enable shared and use new style options

- plugins/gcc4/gcc4-overlay.mk
- plugins/gcc6/gcc6-overlay.mk
- plugins/gcc7/gcc7-overlay.mk
- src/cblas.mk
- src/cloog.mk
- src/gnutls.mk
- src/hdf-eos2.mk
- src/isl.mk
- src/lapack.mk
- src/libffi.mk
- src/opencv.mk
> URL upgrades and fixes

- src/zstd-test.c
- src/zstd.mk
> add zstd library

- src/libssh-1-fixes.patch
- src/libssh.mk
Another SSH library with different focus (and distinct headers/libs). See:
https://www.libssh2.org/libssh2-vs-libssh.html
> add package libssh

- src/libgcrypt.mk
- src/libomemo-test.c
- src/libomemo-test.cmake
- src/libomemo.mk
- src/mxml.mk
> mxml and libomemo: enable shared

- src/nasm.mk
- src/x264.mk
- src/yasm.mk
> Update x264 and use nasm assembler

- src/gc.mk
- src/libatomic_ops.mk
> Update gc to 7.6.0 (and add libatomic_ops because of it)

- src/itpp-1-fixes.patch
- src/itpp.mk
Replaces #1742 with various fixups
- remove extraneous wget change in main Makefile
- disable docs
- enable shared/static
- fix blas/lapack libs
- install pc file
- build test
> Added new module itpp

- src/sdl2-2-no-default-gl-prototypes.patch
The issue for this PR is https://github.com/mxe/mxe/issues/1961
@rcgordon, @slouken would be good to hear from you guys because this should also be fixed upstream. The upstream ticket is https://bugzilla.libsdl.org/show_bug.cgi?id=3944.
> sdl2: disable conflicting GL extension prototypes

- src/autotools.mk
- src/glib.mk
> add dependency package autotools

- Makefile
- tools/skeleton.py
- updates.mk
Initially used in #1960 but should be expanded to #1310
> Makefile: add generic updater function

- plugins/tcl.tk/tktable.mk
- install .pc file,
- install bin/test-pkg.exe compiled with flags by pkg-config,
- install .dll to bin/ and .a, .dll.a to lib/,
- use $(TARGET)-cmake instead of cmake,
- build in `$(BUILD_DIR)` instead of `$(SOURCE_DIR)`,
- do not run target executables with Wine,
- do not download anything while building,
- do not install documentation,
- do not install .exe files except test and build systems,
Thanks!
> Added in Tktable.mk

- src/openblas.mk
> openblas: fix building on single-core machine

- src/libsodium.mk
See https://github.com/mxe/mxe/commit/7890920baad190bcbf4c1455c645c59b69bb7727
> libsodium: update 1.0.6 --> 1.0.15, use GH_CONF, and build out-of-source

- src/cmake.mk
> cmake: update to 3.10

- src/vtk.mk
> vtk: build compile tools once

- src/libao.mk
> libao: disable esd

- docs/index.html
Emu64 used MXE. I added the link in /docs/index.html :)
MXE is a nice Project !!
> add: Emu64 link to index.html #used by

- src/devil-1-fixes.patch
Straightforward case fix.
Also sent upstream here: https://github.com/DentonW/DevIL/pull/71 but it doesn't seem the most active, so I've figured a fix here can help too :)
> Fix devil shared lib compilation

- docs/index.html
Proof:
https://sourceforge.net/projects/psiplus/files/MS-Windows/Personal-Builds/tehnick/
https://github.com/psi-plus/maintenance/tree/master/scripts/win32/cross-compilation-examples
> Add Psi+ to the list of projects which use MXE

- src/gtksourceview.mk
- src/libgda.mk
- src/libsoup.mk
Major thanks to @tonytheodore for all the help, here are the remaining files that need to patched for darwin support.
> fixes remaining compile issues on darwin by using system perl

- src/yaml-cpp.mk
- Updated version and checksum
- Boost dependency replaced with C++11
- Added $(PKG)_GH_CONF setting
> Update yaml-cpp to 0.6.1

- src/osgearth-1-fixes.patch
- src/osgearth.mk
Build is tested for:
```
MXE_TARGETS :=  i686-w64-mingw32.static i686-w64-mingw32.shared \
x86_64-w64-mingw32.static x86_64-w64-mingw32.shared
```
> Add package osgearth

- plugins/examples/qt5-freeze/openssl.mk
Tested for:
```
MXE_TARGETS :=  i686-w64-mingw32.static i686-w64-mingw32.shared \
x86_64-w64-mingw32.static x86_64-w64-mingw32.shared
```
> update qt5-freeze example

- src/ghostscript.mk
It appears that the default static library created with "make libgs" doesn't always work correctly. I had issues where a postscript viewer would only display the .ps files if it was linked against the shared library (same happened for native Linux builds). Creating the static library manually from the object files that were used to build the dll fixes this issue.
> ghostscript: create usable static library, don't use bundled lcms2

- src/poppler.mk
Fix is from @jjbenham (see #1820).
> poppler: disable reference docs (close #1820)

- docs/index.html
Thanks for such a great project!
> add link to wkhtmltopdf in index.html#used_by

- tools/build-pkg.lua
fakeroot hangs in a docker container and is not required (already root), so don't call it if `MXE_BUILD_PKG_NO_FAKEROOT` is set in the environment.
> allow disabling usage of fakeroot via MXE_BUILD_PKG_NO_FAKEROOT

- src/qt.mk
> Install Qt4 translations

- src/glm-test.cpp
- src/glm.mk
> glm: updated and fixed test

- src/hamlib.mk
> update to hamlib v3.3

- Makefile
- docs/index.html
- plugins/native/void/overlay.mk
- src/cmake.mk
> Fix cmake build on void linux

- src/qtifw-1-fixes.patch
- src/qtifw.mk
This installs qt installer framework in mxe. It only makes sense for static targets and the native tools depend on a native Qt installation.
> new package: qtifw

- src/cminpack.mk
- src/freeimage.mk
Hi,
This patch enables the shared build of cminpack
> cminpack shared

- src/glfw3.mk
> glfw3: updated; fixed library rename

- src/flac.mk
- src/sfml-1-fixes-crlf.patch
- src/sfml-1-fixes.patch
- src/sfml.mk
> sfml update

- Makefile
- src/json-c.mk
Ref: https://forums.aws.amazon.com/ann.jspa?annID=6776
Thanks!
> Switch to virtual-hosted style URLs for S3

- plugins/examples/qt5-freeze/qtbase.mk
> plugins/examples/qt5-freeze: Update URL.

- src/libmpeg2.mk
Detected via https-everywhere rules.
> secure/fix a few URLs

- docs/index.html
> Add Dust Racing 2D and Heimer to index.html

- docs/gmsl.html
- ext/__gmsl
- ext/config.guess
- ext/gmsl
We’re currently using two-(almost and-a-half) year old versions.
The new config.guess supports musl among other stuff.
Also, fixed their respective update scripts so they’ll work again.
> Update config.guess and gmsl

- docs/index.html
Since the last release, I use MXE to provide the official release builds of the ScummVM project. Thank you for this great project btw!
> Add ScummVM to the 'Used by' section in index.html

- docs/index.html
Most people should be using Qt5 by now. Let's switch the roles of Qt4
and Qt5, to give more prominence to the latter.
> docs: show how to use Qt 5

- plugins/apps/tor.mk
Builds fine™
`make -j6 MXE_PLUGIN_DIRS='/mxe/plugins/apps/' MXE_TARGETS='x86_64-w64-mingw32.static' tor`
> Bump Tor to 0.4.3.5

- Makefile
- src/mesa.mk
- src/nsis.mk
- src/python-conf.mk
- src/python-mako.mk
- src/python-markupsafe.mk
- src/python-setuptools.mk
- src/scons-local.mk
Tested on darwin with all four targets and both python2/3.
> Improve python and mesa

- src/python-conf.mk
Make sure libdir is always lib, and not lib64
> Add --install-lib to setup.py in python-conf

- src/ms-gsl.mk
add Microsoft c++ guideline support library
> add ms-gsl

- docs/packages.json
- plugins/gcc10/gcc10-overlay.mk
- plugins/gcc11/gcc11-overlay.mk
- plugins/gcc4/gcc4-overlay.mk
- plugins/gcc6/gcc6-overlay.mk
- plugins/gcc7/gcc7-overlay.mk
- plugins/gcc8/gcc8-overlay.mk
- plugins/gcc9/gcc9-overlay.mk
- src/isl.mk
> isl: update URL

- src/libxml2.mk
> Update libxml2 to version 2.9.12

- src/qtbase-1-fixes.patch
- src/qtdeclarative-1-fixes.patch
This supersedes #2680.
Add two bug fix patches for Qt / Qt Declarative.
> Add two qt patches

- src/sdl2_net-2-pkg-config.patch
- src/sdl2_net.mk
See https://github.com/libsdl-org/SDL_net/pull/35
> sdl2_net: Add required libraries to pkgconfig on static build

- src/bzip2.mk
- src/eigen.mk
- src/pcl-1-fixes.patch
Eigen library: Update to v3.4.0 (stable), new pkg source (due to GitLab migration), latest version function update. Bzip2: Change pkg source to official. PCL patch to support latest eigen.
Dear MXE developers,
Thank you very much for such awesome project. I want to contribute some updates. I've compiled all the dependencies. It is working.
> Update: Eigen, Bzip2, PCL

- src/gdb.mk
> Fix gdb build. Fixes #2784

- src/qt/qt6/qt6-qtcharts.mk
- src/qt/qt6/qt6-qtserialport.mk
I used one of the other qt6 modules as template. I tested this and it seems to work.
> qt6: Add qtcharts and qtserialport.

- docs/build-matrix.html
Since the GitHub/Travis bot is broken. I will update the matrix overview manually (`make docs/....`).
> Manual update build matrix

- src/tidy-html5.mk
Update to the current version.
> tidy-html5: update to 5.8.0

- docs/build-matrix.html
- docs/packages.json
- src/nlopt.mk
Update nlopt to the current version.
> Update nlopt to 2.7.1.

- src/gst-plugins-bad.mk
- src/gst-plugins-base.mk
libgstopus plugin is part of this package now
> gst-plugins-base: add build dependency from opus

- src/hiredis-1-fixes.patch
- src/hiredis.mk
Hiredis is a client for Redis, an open-source in-memory database, https://redis.io/.
> hiredis: add package

- tools/copydlldeps.py
This PR references #589 and #2617. Both are closed, but were not fixed in copydlldeps.py
The issue is with 64-bit files (PE32+) files, because the field for `NumberOfRvaAndSizes` is in another location compared to PE32 files.
Reference (Magic): https://learn.microsoft.com/en-us/windows/win32/debug/pe-format#optional-header-image-only
Reference (NumberOfRvaAndSizes): https://learn.microsoft.com/en-us/windows/win32/debug/pe-format#optional-header-windows-specific-fields-image-only
> Adds PE32+ support to copydlldeps.py

- src/libspectre.mk
> update libspectre to v0.2.12

- src/ghostscript.mk
`HAVE_SYS_TIMES_H` must be manually defined as 0 or else the build will fail.
> update ghostscript to v10.02.1

- ext/__gmsl
- ext/config.guess
- ext/gmsl
Upading gsml and the config.guess script to latest versions.
> Update config.guess and gsml

- src/ninja.mk
New version of ninja build system.
Tested with some packages built with ninja.
> ninja: update 1.11.1 -> 1.12.0

- plugins/gcc14/gcc14.patch
https://github.com/gcc-mirror/gcc/commit/a805de33f7be4f6886906ca5f4da493f3b743c76
> gcc14: update __cxa_thread_atexit fix to accepted commit

- src/libnghttp2.mk
This PR adds a recipe for the libnghttp2 library, let me know if I've missed anything. Thanks!
> Add recipe for libnghttp2

- src/sdl3-test.c
- src/sdl3.mk
> sdl3: added preview version 3.1.6

- src/sdl3.mk
update from preview to first official release of sdl3 3.2.0
also see #3096
> sdl3: update 3.1.6 -> 3.2.0

- src/sdl3.mk
https://github.com/libsdl-org/SDL/releases/tag/release-3.2.2
> sdl3: updated 3.2.0 -> 3.2.2

- src/sdl3.mk
https://github.com/libsdl-org/SDL/releases/tag/release-3.2.6
> sdl3: updated 3.2.4 -> 3.2.6

- src/tiff.mk
This updates the download location for tiff and also the update script to match.
> Update download location.

- src/libdeflate.mk
> Add libdeflate.

- src/libidn2-test.c
- src/portaudio-test.c
Fix tests for newer compilers.
> Specify function argument for new C compilers.

- src/quantlib-1-fixes.patch
- src/quantlib.mk
> Add QuantLib.
